### ISSUE TITLE
.NET Framework issues?

### ISSUE THREAD

**Issue by ZachmanAwesomeness** [sonicretro/SonLVL#106]
Program: SonLVL
Build Date: 12/27/2021 21:10:17
OS Version: Microsoft Windows NT 6.2.9200.0
Log:
Operating system: Microsoft Windows NT 6.2.9200.0
System.Configuration.ConfigurationErrorsException: Configuration system failed to initialize ---> System.Configuration.ConfigurationErrorsException: Unrecognized attribute 'jitDebugging'. Note that attribute names are case-sensitive. (C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\machine.config line 30)
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
   at System.Configuration.BaseConfigurationRecord.ThrowIfInitErrors()
   at System.Configuration.ClientConfigurationSystem.EnsureInit(String configKey)
   --- End of inner exception stack trace ---
   at System.Configuration.ConfigurationManager.PrepareConfigSystem()
   at System.Configuration.ConfigurationManager.RefreshSection(String sectionName)
   at System.Configuration.ClientSettingsStore.ReadSettings(String sectionName, Boolean isUserScoped)
   at System.Configuration.LocalFileSettingsProvider.GetPropertyValues(SettingsContext context, SettingsPropertyCollection properties)
   at System.Configuration.SettingsBase.GetPropertiesFromProvider(SettingsProvider provider)
   at System.Configuration.SettingsBase.GetPropertyValueByName(String propertyName)
   at System.Configuration.SettingsBase.get_Item(String propertyName)
   at System.Configuration.ApplicationSettingsBase.GetPropertyValue(String propertyName)
   at System.Configuration.ApplicationSettingsBase.get_Item(String propertyName)
   at SonicRetro.SonLVL.Properties.Settings.get_ShowHUD() in D:\Programs\SonLVL\SonLVL\Properties\Settings.Designer.cs:line 31
   at SonicRetro.SonLVL.Settings.Load() in D:\Programs\SonLVL\SonLVL\Settings.cs:line 82
   at SonicRetro.SonLVL.GUI.MainForm.MainForm_Load(Object sender, EventArgs e) in D:\Programs\SonLVL\SonLVL\MainForm.cs:line 218
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Attempted to open something too and got an error that says:
"Configuration system failed to initialize"

How do I fix this?

**Comment by MainMemory** [comment]
Reinstall the .NET Framework?

**Comment by HadrielWonda** [comment]
You might have a faulty installation so maybe just reinstall the framework
