### ISSUE TITLE
bruh i cant edit any text and art

### ISSUE THREAD

**Issue by Alex123321op** [sonicretro/SonLVL#113]
Program: SonLVL
Build Date: 12/27/2021 21:10:17
OS Version: Microsoft Windows NT 6.2.9200.0
Log:
Operating system: Microsoft Windows NT 6.2.9200.0
Opening INI file "C:\Users\DAFO\Desktop\s2disasm-master\SonPLN.ini"...
Game type is S2.
Loading SEGA Logo...
Loading 8x8 tiles from file "art/nemesis/SEGA.bin", using compression Kosinski...
Loading palette file "art/palettes/Sega screen.bin"...
Source: 16 Destination: 0 Length: 64
Unable to read file "art/nemesis/SEGA.bin" with compression Kosinski:
System.AggregateException: One or more errors occurred. ---> System.IO.IOException: An attempt was made to move the position before the beginning of the stream.
   at System.IO.MemoryStream.Seek(Int64 offset, SeekOrigin loc)
   at SonicRetro.KensSharp.Kosinski.DecodeInternal(Stream source, Stream destination, Int64& decompressedBytes)
   at SonicRetro.KensSharp.Kosinski.Decompress(Stream input, Stream output)
   at SonicRetro.KensSharp.Kosinski.Decompress(String sourceFilePath)
   at SonicRetro.SonLVL.API.Compression.Decompress(String file, CompressionType cmp) in D:\Programs\SonLVL\SonLVLAPI\Compression.cs:line 51
   at SonicRetro.SonLVL.API.LevelData.LoadLevelTiles() in D:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 469
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
   at System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions)
   at System.Threading.Tasks.Parallel.Invoke(Action[] actions)
   at SonicRetro.SonLVL.API.LevelData.LoadLevel(String levelname, Boolean loadGraphics) in D:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 184
   at SonicRetro.SonLVL.GUI.MainForm.backgroundLevelLoader_DoWork(Object sender, DoWorkEventArgs e) in D:\Programs\SonLVL\SonLVL\MainForm.cs:line 574
---> (Inner Exception #0) System.IO.IOException: An attempt was made to move the position before the beginning of the stream.
   at System.IO.MemoryStream.Seek(Int64 offset, SeekOrigin loc)
   at SonicRetro.KensSharp.Kosinski.DecodeInternal(Stream source, Stream destination, Int64& decompressedBytes)
   at SonicRetro.KensSharp.Kosinski.Decompress(Stream input, Stream output)
   at SonicRetro.KensSharp.Kosinski.Decompress(String sourceFilePath)
   at SonicRetro.SonLVL.API.Compression.Decompress(String file, CompressionType cmp) in D:\Programs\SonLVL\SonLVLAPI\Compression.cs:line 51
   at SonicRetro.SonLVL.API.LevelData.LoadLevelTiles() in D:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 469
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

---> (Inner Exception #1) System.FormatException: Level must contain at least one Blocks file!
   at SonicRetro.SonLVL.API.LevelData.LoadLevelBlocks() in D:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 520
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

---> (Inner Exception #2) System.FormatException: Level must contain at least one Chunks file!
   at SonicRetro.SonLVL.API.LevelData.LoadLevelChunks() in D:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 552
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

---> (Inner Exception #3) System.FormatException: Level must contain a Layout file!
   at SonicRetro.SonLVL.API.LevelData.LoadLevelLayout(String levelname) in D:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 625
   at SonicRetro.SonLVL.API.LevelData.<>c__DisplayClass70_0.<LoadLevel>b__0() in D:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 184
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

---> (Inner Exception #4) System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() in D:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 672
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by flamewing** [comment]
> Loading 8x8 tiles from file "art/**_nemesis_**/SEGA.bin", using compression **_Kosinski_**...

You are using the wrong compression format for the art file: the file is a Nemesis-compressed file, and you are trying to read it as Kosinski-compressed file. You probably need to set

```
tilecmp=Nemesis
```

for the Sega screen in `SonPLN.ini`.
