### ISSUE TITLE
Can't load map files even with right sonic 1

### ISSUE THREAD

**Issue by prosonicscool2** [sonicretro/SonLVL#115]
Program: SonLVL
Build Date: 12/27/2021 21:10:17
OS Version: Microsoft Windows NT 6.2.9200.0
Log:
Operating system: Microsoft Windows NT 6.2.9200.0
Opening INI file "C:\Users\gentr_ixpr7gj\OneDrive\Documents\Desktop\sonic hax\Sonic 1 2005 INIs\SonLVL.ini"...
Game type is S1.
Loading Green Hill Zone Act 1...
Loading palette file "../pallet/sonic.bin"...
Source: 0 Destination: 0 Length: 16
Loading 256x256 chunks from file "../map256/ghz.bin", using compression Kosinski...
Loading 16x16 blocks from file "../map16/ghz.bin", using compression Enigma...
8x8 tile file "../artnem/8x8ghz1.bin" not found.
8x8 tile file "../artnem/8x8ghz2.bin" not found.
Loading FG layout from file "../levels/ghz1.bin", using compression Uncompressed...
Loading BG layout from file "../levels/ghzbg.bin", using compression Uncompressed...
Loading FG layout from file "../levels/ghz2.bin", using compression Uncompressed...
Loading FG layout from file "../levels/ghz3.bin", using compression Uncompressed...
Loading FG layout from file "../levels/ending.bin", using compression Uncompressed...
System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
   at SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() in D:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 689
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
   at System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions)
   at System.Threading.Tasks.Parallel.Invoke(Action[] actions)
   at SonicRetro.SonLVL.API.LevelData.LoadLevel(String levelname, Boolean loadGraphics) in D:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 184
   at SonicRetro.SonLVL.GUI.MainForm.backgroundLevelLoader_DoWork(Object sender, DoWorkEventArgs e) in D:\Programs\SonLVL\SonLVL\MainForm.cs:line 574
---> (Inner Exception #0) System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
File name: '../pallet/sonic.bin'
   at SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() in D:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 689
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

 Can anyone help?

**Comment by HyperDondon** [comment]
try disabling onedrive maybe that can work
