### ISSUE TITLE
i literally can't do anything

### ISSUE THREAD

**Issue by Emittey** [sonicretro/SonLVL#117]
Program: SonLVL
Build Date: 12/27/2021 21:10:17
OS Version: Microsoft Windows NT 6.2.9200.0
Log:
Operating system: Microsoft Windows NT 6.2.9200.0
Opening INI file "C:\Users\storm\Desktop\Documents\ZIP extracts\SONK\levle\Sonic 2 2007 INIs\SonLVL.ini"...
Game type is S2.
Loading Chemical Plant Zone Act 1...
Loading palette file "../art/palettes/SonicAndTails.bin"...
Source: 0 Destination: 0 Length: 16
16x16 block file "../mappings/16x16/CPZ_DEZ.bin" not found.
8x8 tile file "../art/kosinski/CPZ_DEZ.bin" not found.
128x128 chunk file "../mappings/128x128/CPZ_DEZ.bin" not found.
Layout file "../level/layout/CPZ_1.bin" not found.
Layout file "../level/layout/CPZ_2.bin" not found.
Layout file "../level/layout/DEZ.bin" not found.
System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
   at SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() in D:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 689
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
   at System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions)
   at System.Threading.Tasks.Parallel.Invoke(Action[] actions)
   at SonicRetro.SonLVL.API.LevelData.LoadLevel(String levelname, Boolean loadGraphics) in D:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 184
   at SonicRetro.SonLVL.GUI.MainForm.backgroundLevelLoader_DoWork(Object sender, DoWorkEventArgs e) in D:\Programs\SonLVL\SonLVL\MainForm.cs:line 574
---> (Inner Exception #0) System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
File name: '../art/palettes/SonicAndTails.bin'
   at SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() in D:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 689
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

i really have no idea what to do

**Comment by Caverns4** [comment]
What are you trying to do?
Your disassmbly should simply have a sub folder in the main directory called "SonLvL INI files" or something like that. The location this INI file you're loading in is too deep.

Put simply, instead of C:\Users\storm\Desktop\Documents\ZIP extracts\SONK\levle\Sonic 2 2007 INIs\SonLVL.ini"
try putting your SonLvl stuff in just C:\Users\storm\Desktop\Documents\ZIP extracts\SONK\Sonic 2 2007 INIs\SonLVL.ini"
