### ISSUE TITLE
There is a bug at the start menu like when I load Green Hill Act 1. It says there is a bug i have the updater too. When I loaded the zone it said error and all I see is white.

### ISSUE THREAD

**Issue by sonikisking** [sonicretro/SonLVL#131]
Program: SonLVL
Build Date: 07/18/2022 03:48:03
OS Version: Microsoft Windows NT 6.2.9200.0
Log:
Operating system: Microsoft Windows NT 6.2.9200.0
Opening INI file "C:\Users\momoo\Downloads\SonLVL Updater\Sonic 1 Git INIs\SonLVL.rev01.ini"...
Game type is S1.
Loading Green Hill Zone Act 1...
8x8 tile file "../artnem/8x8 - GHZ1.bin" not found.
Loading 16x16 blocks from file "../map16/GHZ.bin", using compression Enigma...
Loading 256x256 chunks from file "../map256/GHZ.bin", using compression Kosinski...
8x8 tile file "../artnem/8x8 - GHZ2.bin" not found.
Loading FG layout from file "../levels/ghz1.bin", using compression Uncompressed...
Loading BG layout from file "../levels/ghzbg.bin", using compression Uncompressed...
Loading palette file "../palette/Sonic.bin"...
Source: 0 Destination: 0 Length: 16
Loading FG layout from file "../levels/ghz2.bin", using compression Uncompressed...
Loading FG layout from file "../levels/ghz3.bin", using compression Uncompressed...
Loading FG layout from file "../levels/ending.bin", using compression Uncompressed...
System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
   at SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 676
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
   at System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions)
   at System.Threading.Tasks.Parallel.Invoke(Action[] actions)
   at SonicRetro.SonLVL.API.LevelData.LoadLevel(String levelname, Boolean loadGraphics) in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 166
   at SonicRetro.SonLVL.GUI.MainForm.backgroundLevelLoader_DoWork(Object sender, DoWorkEventArgs e) in C:\Programs\SonLVL\SonLVL\MainForm.cs:line 567
---> (Inner Exception #0) System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
File name: '../palette/Sonic.bin'
   at SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 676
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by sonikisking** [comment]
Program: SonLVL
Build Date: 07/18/2022 03:48:03
OS Version: Microsoft Windows NT 6.2.9200.0
Log:
Operating system: Microsoft Windows NT 6.2.9200.0
Opening INI file "C:\Users\momoo\Downloads\SonLVL Updater\Sonic 1 Git INIs\SonLVL.rev01.ini"...
Game type is S1.
Loading Green Hill Zone Act 1...
8x8 tile file "../artnem/8x8 - GHZ1.bin" not found.
Loading 16x16 blocks from file "../map16/GHZ.bin", using compression Enigma...
Loading 256x256 chunks from file "../map256/GHZ.bin", using compression Kosinski...
8x8 tile file "../artnem/8x8 - GHZ2.bin" not found.
Loading FG layout from file "../levels/ghz1.bin", using compression Uncompressed...
Loading BG layout from file "../levels/ghzbg.bin", using compression Uncompressed...
Loading palette file "../palette/Sonic.bin"...
Source: 0 Destination: 0 Length: 16
Loading FG layout from file "../levels/ghz2.bin", using compression Uncompressed...
Loading FG layout from file "../levels/ghz3.bin", using compression Uncompressed...
Loading FG layout from file "../levels/ending.bin", using compression Uncompressed...
System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
   at SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 676
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
   at System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions)
   at System.Threading.Tasks.Parallel.Invoke(Action[] actions)
   at SonicRetro.SonLVL.API.LevelData.LoadLevel(String levelname, Boolean loadGraphics) in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 166
   at SonicRetro.SonLVL.GUI.MainForm.backgroundLevelLoader_DoWork(Object sender, DoWorkEventArgs e) in C:\Programs\SonLVL\SonLVL\MainForm.cs:line 567
---> (Inner Exception #0) System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
File name: '../palette/Sonic.bin'
   at SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 676
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

Saving Green Hill Zone Act 1...
System.AggregateException: One or more errors occurred. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\momoo\Downloads\SonLVL Updater\palette\Sonic.bin'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at SonicRetro.SonLVL.API.LevelData.SaveLevelPalette() in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 1092
   at System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.<Invoke>b__0()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions)
   at SonicRetro.SonLVL.API.LevelData.SaveLevel() in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 949
   at SonicRetro.SonLVL.GUI.MainForm.saveToolStripMenuItem_Click(Object sender, EventArgs e) in C:\Programs\SonLVL\SonLVL\MainForm.cs:line 905
   at SonicRetro.SonLVL.GUI.MainForm.buildAndRunToolStripMenuItem_Click(Object sender, EventArgs e) in C:\Programs\SonLVL\SonLVL\MainForm.cs:line 941
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
---> (Inner Exception #0) System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\momoo\Downloads\SonLVL Updater\palette\Sonic.bin'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at SonicRetro.SonLVL.API.LevelData.SaveLevelPalette() in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 1092
   at System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.<Invoke>b__0()<---

---> (Inner Exception #1) System.NullReferenceException: Object reference not set to an instance of an object.
   at SonicRetro.SonLVL.API.LevelData.SaveLevelObjects() in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 1142
   at System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.<Invoke>b__0()<---

---> (Inner Exception #2) System.NullReferenceException: Object reference not set to an instance of an object.
   at SonicRetro.SonLVL.API.LevelData.SaveLevelStartPositions() in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 1188
   at System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.<Invoke>b__0()<---

**Comment by sonikisking** [comment]
Program: SonLVL
Build Date: 07/18/2022 03:48:03
OS Version: Microsoft Windows NT 6.2.9200.0
Log:
Operating system: Microsoft Windows NT 6.2.9200.0
Opening INI file "C:\Users\momoo\Downloads\SonLVL Updater\Sonic 1 Git INIs\SonLVL.rev01.ini"...
Game type is S1.
Loading Green Hill Zone Act 1...
8x8 tile file "../artnem/8x8 - GHZ1.bin" not found.
Loading 16x16 blocks from file "../map16/GHZ.bin", using compression Enigma...
Loading 256x256 chunks from file "../map256/GHZ.bin", using compression Kosinski...
8x8 tile file "../artnem/8x8 - GHZ2.bin" not found.
Loading FG layout from file "../levels/ghz1.bin", using compression Uncompressed...
Loading BG layout from file "../levels/ghzbg.bin", using compression Uncompressed...
Loading palette file "../palette/Sonic.bin"...
Source: 0 Destination: 0 Length: 16
Loading FG layout from file "../levels/ghz2.bin", using compression Uncompressed...
Loading FG layout from file "../levels/ghz3.bin", using compression Uncompressed...
Loading FG layout from file "../levels/ending.bin", using compression Uncompressed...
System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
   at SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 676
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
   at System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions)
   at System.Threading.Tasks.Parallel.Invoke(Action[] actions)
   at SonicRetro.SonLVL.API.LevelData.LoadLevel(String levelname, Boolean loadGraphics) in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 166
   at SonicRetro.SonLVL.GUI.MainForm.backgroundLevelLoader_DoWork(Object sender, DoWorkEventArgs e) in C:\Programs\SonLVL\SonLVL\MainForm.cs:line 567
---> (Inner Exception #0) System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
File name: '../palette/Sonic.bin'
   at SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 676
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

Saving Green Hill Zone Act 1...
System.AggregateException: One or more errors occurred. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\momoo\Downloads\SonLVL Updater\palette\Sonic.bin'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at SonicRetro.SonLVL.API.LevelData.SaveLevelPalette() in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 1092
   at System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.<Invoke>b__0()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions)
   at SonicRetro.SonLVL.API.LevelData.SaveLevel() in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 949
   at SonicRetro.SonLVL.GUI.MainForm.saveToolStripMenuItem_Click(Object sender, EventArgs e) in C:\Programs\SonLVL\SonLVL\MainForm.cs:line 905
   at SonicRetro.SonLVL.GUI.MainForm.buildAndRunToolStripMenuItem_Click(Object sender, EventArgs e) in C:\Programs\SonLVL\SonLVL\MainForm.cs:line 941
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
---> (Inner Exception #0) System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\momoo\Downloads\SonLVL Updater\palette\Sonic.bin'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at SonicRetro.SonLVL.API.LevelData.SaveLevelPalette() in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 1092
   at System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.<Invoke>b__0()<---

---> (Inner Exception #1) System.NullReferenceException: Object reference not set to an instance of an object.
   at SonicRetro.SonLVL.API.LevelData.SaveLevelObjects() in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 1142
   at System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.<Invoke>b__0()<---

---> (Inner Exception #2) System.NullReferenceException: Object reference not set to an instance of an object.
   at SonicRetro.SonLVL.API.LevelData.SaveLevelStartPositions() in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 1188
   at System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.<Invoke>b__0()<---

Opening INI file "C:\Users\momoo\Downloads\SonLVL Updater\Sonic 1 Git INIs\SonLVL.ini"...
Game type is S1.
Loading Green Hill Zone Act 1...
Loading 16x16 blocks from file "../map16/GHZ.bin", using compression Enigma...
Loading 8x8 tiles from file "../artnem/8x8 - GHZ1.bin", using compression Nemesis...
Loading 256x256 chunks from file "../map256/GHZ.bin", using compression Kosinski...
Loading FG layout from file "../levels/ghz1.bin", using compression Uncompressed...
Loading BG layout from file "../levels/ghzbg.bin", using compression Uncompressed...
Loading FG layout from file "../levels/ghz2.bin", using compression Uncompressed...
Loading palette file "../palette/Sonic.bin"...
Source: 0 Destination: 0 Length: 16
Loading FG layout from file "../levels/ghz3.bin", using compression Uncompressed...
Loading FG layout from file "../levels/ending.bin", using compression Uncompressed...
Loading 8x8 tiles from file "../artnem/8x8 - GHZ2.bin", using compression Nemesis...
System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
   at SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 676
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
   at System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions)
   at System.Threading.Tasks.Parallel.Invoke(Action[] actions)
   at SonicRetro.SonLVL.API.LevelData.LoadLevel(String levelname, Boolean loadGraphics) in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 166
   at SonicRetro.SonLVL.GUI.MainForm.backgroundLevelLoader_DoWork(Object sender, DoWorkEventArgs e) in C:\Programs\SonLVL\SonLVL\MainForm.cs:line 567
---> (Inner Exception #0) System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
File name: '../palette/Sonic.bin'
   at SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 676
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

Opening INI file "C:\Users\momoo\Downloads\SonLVL Updater\Sonic 1 Git INIs\SonLVL.rev01.ini"...
Game type is S1.
Loading Green Hill Zone Act 1...
Loading 16x16 blocks from file "../map16/GHZ.bin", using compression Enigma...
Loading 8x8 tiles from file "../artnem/8x8 - GHZ1.bin", using compression Nemesis...
Loading 8x8 tiles from file "../artnem/8x8 - GHZ2.bin", using compression Nemesis...
Loading FG layout from file "../levels/ghz1.bin", using compression Uncompressed...
Loading palette file "../palette/Sonic.bin"...
Source: 0 Destination: 0 Length: 16
Loading BG layout from file "../levels/ghzbg.bin", using compression Uncompressed...
Loading 256x256 chunks from file "../map256/GHZ.bin", using compression Kosinski...
Loading FG layout from file "../levels/ghz2.bin", using compression Uncompressed...
Loading FG layout from file "../levels/ghz3.bin", using compression Uncompressed...
Loading FG layout from file "../levels/ending.bin", using compression Uncompressed...
System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
   at SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 676
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
   at System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions)
   at System.Threading.Tasks.Parallel.Invoke(Action[] actions)
   at SonicRetro.SonLVL.API.LevelData.LoadLevel(String levelname, Boolean loadGraphics) in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 166
   at SonicRetro.SonLVL.GUI.MainForm.backgroundLevelLoader_DoWork(Object sender, DoWorkEventArgs e) in C:\Programs\SonLVL\SonLVL\MainForm.cs:line 567
---> (Inner Exception #0) System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
File name: '../palette/Sonic.bin'
   at SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 676
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by Caverns4** [comment]
You need to load the "Sonic 1 Git INIs" folder from inside your actual Sonic 1 git disassembly. It should come with a SonLvl folder by default.
