### ISSUE TITLE
I can't restore green hill zone into sonic 2 and here's why:

### ISSUE THREAD

**Issue by Hex2013** [sonicretro/SonLVL#152]
Program: SonLVL
Build Date: 03/22/2023 18:17:11
OS Version: Microsoft Windows NT 6.2.9200.0
Log:
Operating system: Microsoft Windows NT 6.2.9200.0
Opening INI file "C:\Users\rylan\OneDrive\Desktop\harlys stuff (again)\S2LVL_B5\Sonic 2 2007 INIs\SonLVL.ini"...
Game type is S2.
Loading Emerald Hill Zone Act 1...
16x16 block file "../mappings/16x16/EHZ.bin" not found.
128x128 chunk file "../mappings/128x128/EHZ_HTZ.bin" not found.
Loading palette file "../art/palettes/SonicAndTails.bin"...
Source: 0 Destination: 0 Length: 16
8x8 tile file "../art/kosinski/EHZ_HTZ.bin" not found.
Layout file "../level/layout/EHZ_1.bin" not found.
Layout file "../level/layout/EHZ_2.bin" not found.
Layout file "../level/layout/HTZ_1.bin" not found.
Layout file "../level/layout/HTZ_2.bin" not found.
System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
   at SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 691
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
   at System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions)
   at System.Threading.Tasks.Parallel.Invoke(Action[] actions)
   at SonicRetro.SonLVL.API.LevelData.LoadLevel(String levelname, Boolean loadGraphics) in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 184
   at SonicRetro.SonLVL.GUI.MainForm.backgroundLevelLoader_DoWork(Object sender, DoWorkEventArgs e) in C:\Programs\SonLVL\SonLVL\MainForm.cs:line 574
---> (Inner Exception #0) System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
File name: '../art/palettes/SonicAndTails.bin'
   at SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 691
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

Loading Wing Fortress Zone...
Loading palette file "../art/palettes/SonicAndTails.bin"...
Source: 0 Destination: 0 Length: 16
8x8 tile file "../art/kosinski/WFZ_SCZ.bin" not found.
Layout file "../level/layout/WFZ.bin" not found.
16x16 block file "../mappings/16x16/WFZ_SCZ.bin" not found.
128x128 chunk file "../mappings/128x128/WFZ_SCZ.bin" not found.
8x8 tile file "../art/kosinski/WFZ_Supp.bin" not found.
Layout file "../level/layout/SCZ.bin" not found.
System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
   at SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 691
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
   at System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions)
   at System.Threading.Tasks.Parallel.Invoke(Action[] actions)
   at SonicRetro.SonLVL.API.LevelData.LoadLevel(String levelname, Boolean loadGraphics) in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 184
   at SonicRetro.SonLVL.GUI.MainForm.backgroundLevelLoader_DoWork(Object sender, DoWorkEventArgs e) in C:\Programs\SonLVL\SonLVL\MainForm.cs:line 574
---> (Inner Exception #0) System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
File name: '../art/palettes/SonicAndTails.bin'
   at SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 691
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

Opening INI file "C:\Users\rylan\OneDrive\Desktop\harlys stuff (again)\S2LVL_B5\Sonic 2 2007 INIs\SonLVL.ini"...
Game type is S2.
Loading Emerald Hill Zone Act 1...
16x16 block file "../mappings/16x16/EHZ.bin" not found.
128x128 chunk file "../mappings/128x128/EHZ_HTZ.bin" not found.
Layout file "../level/layout/EHZ_1.bin" not found.
Loading palette file "../art/palettes/SonicAndTails.bin"...
Source: 0 Destination: 0 Length: 16
Layout file "../level/layout/EHZ_2.bin" not found.
8x8 tile file "../art/kosinski/EHZ_HTZ.bin" not found.
Layout file "../level/layout/HTZ_1.bin" not found.
Layout file "../level/layout/HTZ_2.bin" not found.
System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
   at SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 691
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
   at System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions)
   at System.Threading.Tasks.Parallel.Invoke(Action[] actions)
   at SonicRetro.SonLVL.API.LevelData.LoadLevel(String levelname, Boolean loadGraphics) in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 184
   at SonicRetro.SonLVL.GUI.MainForm.backgroundLevelLoader_DoWork(Object sender, DoWorkEventArgs e) in C:\Programs\SonLVL\SonLVL\MainForm.cs:line 574
---> (Inner Exception #0) System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
File name: '../art/palettes/SonicAndTails.bin'
   at SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 691
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

Opening INI file "C:\Users\rylan\OneDrive\Desktop\harlys stuff (again)\S2LVL_B5\Sonic 2 2007 INIs\SonLVL.ini"...
Game type is S2.
Loading Emerald Hill Zone Act 1...
Loading palette file "../art/palettes/SonicAndTails.bin"...
Source: 0 Destination: 0 Length: 16
8x8 tile file "../art/kosinski/EHZ_HTZ.bin" not found.
16x16 block file "../mappings/16x16/EHZ.bin" not found.
Layout file "../level/layout/EHZ_1.bin" not found.
128x128 chunk file "../mappings/128x128/EHZ_HTZ.bin" not found.
Layout file "../level/layout/EHZ_2.bin" not found.
Layout file "../level/layout/HTZ_1.bin" not found.
Layout file "../level/layout/HTZ_2.bin" not found.
System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
   at SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 691
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
   at System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions)
   at System.Threading.Tasks.Parallel.Invoke(Action[] actions)
   at SonicRetro.SonLVL.API.LevelData.LoadLevel(String levelname, Boolean loadGraphics) in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 184
   at SonicRetro.SonLVL.GUI.MainForm.backgroundLevelLoader_DoWork(Object sender, DoWorkEventArgs e) in C:\Programs\SonLVL\SonLVL\MainForm.cs:line 574
---> (Inner Exception #0) System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
File name: '../art/palettes/SonicAndTails.bin'
   at SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 691
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

Opening INI file "C:\Users\rylan\OneDrive\Desktop\harlys stuff (again)\S2LVL_B5\Sonic 2 2007 INIs\SonLVL.ini"...
Game type is S2.
Loading Emerald Hill Zone Act 1...
16x16 block file "../mappings/16x16/EHZ.bin" not found.
128x128 chunk file "../mappings/128x128/EHZ_HTZ.bin" not found.
Loading palette file "../art/palettes/SonicAndTails.bin"...
Source: 0 Destination: 0 Length: 16
Layout file "../level/layout/EHZ_1.bin" not found.
8x8 tile file "../art/kosinski/EHZ_HTZ.bin" not found.
Layout file "../level/layout/EHZ_2.bin" not found.
Layout file "../level/layout/HTZ_1.bin" not found.
Layout file "../level/layout/HTZ_2.bin" not found.
System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
   at SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 691
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
   at System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions)
   at System.Threading.Tasks.Parallel.Invoke(Action[] actions)
   at SonicRetro.SonLVL.API.LevelData.LoadLevel(String levelname, Boolean loadGraphics) in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 184
   at SonicRetro.SonLVL.GUI.MainForm.backgroundLevelLoader_DoWork(Object sender, DoWorkEventArgs e) in C:\Programs\SonLVL\SonLVL\MainForm.cs:line 574
---> (Inner Exception #0) System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
File name: '../art/palettes/SonicAndTails.bin'
   at SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 691
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

Loading Emerald Hill Zone Act 2...
16x16 block file "../mappings/16x16/EHZ.bin" not found.
128x128 chunk file "../mappings/128x128/EHZ_HTZ.bin" not found.
Loading palette file "../art/palettes/SonicAndTails.bin"...
Source: 0 Destination: 0 Length: 16
Layout file "../level/layout/EHZ_2.bin" not found.
Layout file "../level/layout/EHZ_1.bin" not found.
8x8 tile file "../art/kosinski/EHZ_HTZ.bin" not found.
Layout file "../level/layout/HTZ_1.bin" not found.
Layout file "../level/layout/HTZ_2.bin" not found.
System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
   at SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 691
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
   at System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions)
   at System.Threading.Tasks.Parallel.Invoke(Action[] actions)
   at SonicRetro.SonLVL.API.LevelData.LoadLevel(String levelname, Boolean loadGraphics) in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 184
   at SonicRetro.SonLVL.GUI.MainForm.backgroundLevelLoader_DoWork(Object sender, DoWorkEventArgs e) in C:\Programs\SonLVL\SonLVL\MainForm.cs:line 574
---> (Inner Exception #0) System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
File name: '../art/palettes/SonicAndTails.bin'
   at SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 691
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

Loading Emerald Hill Zone Act 1...
16x16 block file "../mappings/16x16/EHZ.bin" not found.
128x128 chunk file "../mappings/128x128/EHZ_HTZ.bin" not found.
Layout file "../level/layout/EHZ_1.bin" not found.
Loading palette file "../art/palettes/SonicAndTails.bin"...
Source: 0 Destination: 0 Length: 16
Layout file "../level/layout/EHZ_2.bin" not found.
8x8 tile file "../art/kosinski/EHZ_HTZ.bin" not found.
Layout file "../level/layout/HTZ_1.bin" not found.
Layout file "../level/layout/HTZ_2.bin" not found.
System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
   at SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 691
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
   at System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions)
   at System.Threading.Tasks.Parallel.Invoke(Action[] actions)
   at SonicRetro.SonLVL.API.LevelData.LoadLevel(String levelname, Boolean loadGraphics) in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 184
   at SonicRetro.SonLVL.GUI.MainForm.backgroundLevelLoader_DoWork(Object sender, DoWorkEventArgs e) in C:\Programs\SonLVL\SonLVL\MainForm.cs:line 574
---> (Inner Exception #0) System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
File name: '../art/palettes/SonicAndTails.bin'
   at SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 691
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by Hex2013** [comment]
You want to see it the file with the problem? here: 
[s2disasm-master.zip](https://github.com/sonicretro/SonLVL/files/12060529/s2disasm-master.zip)
