### ISSUE TITLE
tryna load s2: secret zones levels

### ISSUE THREAD

**Issue by NickArcadeNerd** [sonicretro/SonLVL#154]
It says something about .NET framework but i dont know what version to download

Program: SonLVL
Build Date: 03/22/2023 18:17:11
OS Version: Microsoft Windows NT 6.2.9200.0
Log:
Operating system: Microsoft Windows NT 6.2.9200.0
Opening INI file "C:\Users\archieyoshi\Desktop\SONLVL\SonLVL.ini"...
Game type is S2.
Opening INI file "C:\Users\archieyoshi\Desktop\SONLVL\Updater.ini"...
Game type is S2.
Opening INI file "C:\Users\archieyoshi\Desktop\Disassemblies\Sonic 2 The Secret Zones - Copy\Sonic 2 Git INIs\SonLVL.ini"...
Game type is S2.
Loading Wood Zone Act 1...
Loading 16x16 blocks from file "../mappings/16x16/WZ.bin", using compression Kosinski...
Loading 128x128 chunks from file "../mappings/128x128/WZ.bin", using compression Kosinski...
Loading 8x8 tiles from file "../art/kosinski/WZ.bin", using compression Kosinski...
Loading palette file "../art/palettes/SonicAndTails.bin"...
Source: 0 Destination: 0 Length: 16
Loading palette file "../art/palettes/Wood Zone.bin"...
Source: 0 Destination: 16 Length: 48
Loading layout from file "../level/layout/WZ_1.bin", using compression Kosinski...
Loading layout from file "../level/layout/WZ_2.bin", using compression Kosinski...
Loading object definition file "obj.ini".
Loading object definition file "objWZ.ini".
Loading ObjectDefinition type S2ObjectDefinitions.Common.PathSwapper from "Common\PathSwapper.cs"...
Loading type from cached assembly "dllcache\S2ObjectDefinitions.Common.PathSwapper.dll"...
Loading type from cached assembly "dllcache\S2ObjectDefinitions.Common.Spikes.dll"...
Object definition 36 failed to initialize!
System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
   at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
   at System.Reflection.Assembly.LoadFile(String path)
   at SonicRetro.SonLVL.API.XMLObjectDefinition.Init(ObjectData data) in C:\Programs\SonLVL\SonLVLAPI\ObjectDefinition.cs:line 824
   at SonicRetro.SonLVL.API.LevelData.<>c__DisplayClass102_0.<InitObjectDefinitions>b__0(KeyValuePair`2 group) in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 1580
System.AggregateException: One or more errors occurred. ---> System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
   at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
   at System.Reflection.Assembly.LoadFile(String path)
   at SonicRetro.SonLVL.API.LevelData.<>c__DisplayClass102_0.<InitObjectDefinitions>b__0(KeyValuePair`2 group) in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 1530
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at SonicRetro.SonLVL.API.LevelData.InitObjectDefinitions() in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 1507
   at SonicRetro.SonLVL.API.LevelData.LoadLevel(String levelname, Boolean loadGraphics) in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 321
   at SonicRetro.SonLVL.GUI.MainForm.backgroundLevelLoader_DoWork(Object sender, DoWorkEventArgs e) in C:\Programs\SonLVL\SonLVL\MainForm.cs:line 574
---> (Inner Exception #0) System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
   at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
   at System.Reflection.Assembly.LoadFile(String path)
   at SonicRetro.SonLVL.API.LevelData.<>c__DisplayClass102_0.<InitObjectDefinitions>b__0(KeyValuePair`2 group) in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 1530
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---

Loading Wood Zone Act 1...
Loading 8x8 tiles from file "../art/kosinski/WZ.bin", using compression Kosinski...
Loading 16x16 blocks from file "../mappings/16x16/WZ.bin", using compression Kosinski...
Loading 128x128 chunks from file "../mappings/128x128/WZ.bin", using compression Kosinski...
Loading layout from file "../level/layout/WZ_1.bin", using compression Kosinski...
Loading palette file "../art/palettes/SonicAndTails.bin"...
Source: 0 Destination: 0 Length: 16
Loading palette file "../art/palettes/Wood Zone.bin"...
Source: 0 Destination: 16 Length: 48
Loading layout from file "../level/layout/WZ_2.bin", using compression Kosinski...
Loading object definition file "obj.ini".
Loading object definition file "objWZ.ini".
Loading ObjectDefinition type S2ObjectDefinitions.Common.PathSwapper from "Common\PathSwapper.cs"...
Loading type from cached assembly "dllcache\S2ObjectDefinitions.Common.PathSwapper.dll"...
Loading type from cached assembly "dllcache\S2ObjectDefinitions.Common.Spikes.dll"...
Object definition 36 failed to initialize!
System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
   at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
   at System.Reflection.Assembly.LoadFile(String path)
   at SonicRetro.SonLVL.API.XMLObjectDefinition.Init(ObjectData data) in C:\Programs\SonLVL\SonLVLAPI\ObjectDefinition.cs:line 824
   at SonicRetro.SonLVL.API.LevelData.<>c__DisplayClass102_0.<InitObjectDefinitions>b__0(KeyValuePair`2 group) in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 1580
System.AggregateException: One or more errors occurred. ---> System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
   at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
   at System.Reflection.Assembly.LoadFile(String path)
   at SonicRetro.SonLVL.API.LevelData.<>c__DisplayClass102_0.<InitObjectDefinitions>b__0(KeyValuePair`2 group) in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 1530
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at SonicRetro.SonLVL.API.LevelData.InitObjectDefinitions() in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 1507
   at SonicRetro.SonLVL.API.LevelData.LoadLevel(String levelname, Boolean loadGraphics) in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 321
   at SonicRetro.SonLVL.GUI.MainForm.backgroundLevelLoader_DoWork(Object sender, DoWorkEventArgs e) in C:\Programs\SonLVL\SonLVL\MainForm.cs:line 574
---> (Inner Exception #0) System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
   at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
   at System.Reflection.Assembly.LoadFile(String path)
   at SonicRetro.SonLVL.API.LevelData.<>c__DisplayClass102_0.<InitObjectDefinitions>b__0(KeyValuePair`2 group) in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 1530
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---

Loading Wood Zone Act 1...
Loading palette file "../art/palettes/SonicAndTails.bin"...
Source: 0 Destination: 0 Length: 16
Loading layout from file "../level/layout/WZ_1.bin", using compression Kosinski...
Loading palette file "../art/palettes/Wood Zone.bin"...
Source: 0 Destination: 16 Length: 48
Loading 128x128 chunks from file "../mappings/128x128/WZ.bin", using compression Kosinski...
Loading 8x8 tiles from file "../art/kosinski/WZ.bin", using compression Kosinski...
Loading 16x16 blocks from file "../mappings/16x16/WZ.bin", using compression Kosinski...
Loading layout from file "../level/layout/WZ_2.bin", using compression Kosinski...
Loading object definition file "obj.ini".
Loading object definition file "objWZ.ini".
Loading ObjectDefinition type S2ObjectDefinitions.Common.PathSwapper from "Common\PathSwapper.cs"...
Loading type from cached assembly "dllcache\S2ObjectDefinitions.Common.PathSwapper.dll"...
Loading ObjectDefinition type S2ObjectDefinitions.Common.InvisibleBlock from "Common\InvisibleBlock.cs"...
Loading type from cached assembly "dllcache\S2ObjectDefinitions.Common.InvisibleBlock.dll"...
Loading type from cached assembly "dllcache\S2ObjectDefinitions.ARZ.SwingingPlatform.dll"...
Loading type from cached assembly "dllcache\S2ObjectDefinitions.Common.Spikes.dll"...
Object definition 36 failed to initialize!
System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
   at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
   at System.Reflection.Assembly.LoadFile(String path)
   at SonicRetro.SonLVL.API.XMLObjectDefinition.Init(ObjectData data) in C:\Programs\SonLVL\SonLVLAPI\ObjectDefinition.cs:line 824
   at SonicRetro.SonLVL.API.LevelData.<>c__DisplayClass102_0.<InitObjectDefinitions>b__0(KeyValuePair`2 group) in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 1580
Object definition 15 failed to initialize!
System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
   at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
   at System.Reflection.Assembly.LoadFile(String path)
   at SonicRetro.SonLVL.API.XMLObjectDefinition.Init(ObjectData data) in C:\Programs\SonLVL\SonLVLAPI\ObjectDefinition.cs:line 824
   at SonicRetro.SonLVL.API.LevelData.<>c__DisplayClass102_0.<InitObjectDefinitions>b__0(KeyValuePair`2 group) in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 1580
System.AggregateException: One or more errors occurred. ---> System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
   at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
   at System.Reflection.Assembly.LoadFile(String path)
   at SonicRetro.SonLVL.API.LevelData.<>c__DisplayClass102_0.<InitObjectDefinitions>b__0(KeyValuePair`2 group) in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 1530
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at SonicRetro.SonLVL.API.LevelData.InitObjectDefinitions() in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 1507
   at SonicRetro.SonLVL.API.LevelData.LoadLevel(String levelname, Boolean loadGraphics) in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 321
   at SonicRetro.SonLVL.GUI.MainForm.backgroundLevelLoader_DoWork(Object sender, DoWorkEventArgs e) in C:\Programs\SonLVL\SonLVL\MainForm.cs:line 574
---> (Inner Exception #0) System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
   at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
   at System.Reflection.Assembly.LoadFile(String path)
   at SonicRetro.SonLVL.API.LevelData.<>c__DisplayClass102_0.<InitObjectDefinitions>b__0(KeyValuePair`2 group) in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 1530
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---

---> (Inner Exception #1) System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
   at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
   at System.Reflection.Assembly.LoadFile(String path)
   at SonicRetro.SonLVL.API.LevelData.<>c__DisplayClass102_0.<InitObjectDefinitions>b__0(KeyValuePair`2 group) in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 1530
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---

**Comment by NickArcadeNerd** [comment]
Keep in mind, I'm not trying to plagarise or anything, I just wanted to look behind the scenes of my favourite ROM hack.

**Comment by MainMemory** [comment]
Your install of SonLVL and/or the disassembly is marked as being "from the Internet", you need to unblock it from the file Properties.

**Comment by NickArcadeNerd** [comment]
huh, thanks!

**Comment by NickArcadeNerd** [comment]
alright, where do you make it trust the file though?

**Comment by NickArcadeNerd** [comment]
where in the file properties

**Comment by MainMemory** [comment]
It should be a button on the main page of the Properties dialog. Check the EXE and DLL files for SonLVL, or maybe the folders themselves.
