### ISSUE TITLE
Porting Hidden Palace S2 Version to SonLVL Issue

### ISSUE THREAD

**Issue by FMPJ3** [sonicretro/SonLVL#169]
Please help ive been following a video guide by clownacy for SonLVL but always comes up with the same issue

Program: SonLVL
Build Date: 03/22/2023 18:17:11
OS Version: Microsoft Windows NT 6.2.9200.0
Log:
Operating system: Microsoft Windows NT 6.2.9200.0
Opening INI file "D:\ROM Hacks\s2disasm-master HPZ Restoration\SonLVL INI Files\SonLVL.ini"...
Game type is S2.
Loading Hidden Palace Zone...
Loading 16x16 blocks from file "../mappings/16x16/HPZ.kos", using compression Kosinski...
Loading 128x128 chunks from file "../mappings/128x128/HPZ.kos", using compression Kosinski...
8x8 tile file "../art/layout/HPZ.kps" not found.
System.AggregateException: One or more errors occurred. ---> System.FormatException: Level must contain a Layout file!
   at SonicRetro.SonLVL.API.LevelData.LoadLevelLayout(String levelname) in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 627
   at SonicRetro.SonLVL.API.LevelData.<>c__DisplayClass70_0.<LoadLevel>b__0() in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 184
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
   at System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions)
   at System.Threading.Tasks.Parallel.Invoke(Action[] actions)
   at SonicRetro.SonLVL.API.LevelData.LoadLevel(String levelname, Boolean loadGraphics) in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 184
   at SonicRetro.SonLVL.GUI.MainForm.backgroundLevelLoader_DoWork(Object sender, DoWorkEventArgs e) in C:\Programs\SonLVL\SonLVL\MainForm.cs:line 574
---> (Inner Exception #0) System.FormatException: Level must contain a Layout file!
   at SonicRetro.SonLVL.API.LevelData.LoadLevelLayout(String levelname) in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 627
   at SonicRetro.SonLVL.API.LevelData.<>c__DisplayClass70_0.<LoadLevel>b__0() in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 184
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

---> (Inner Exception #1) System.FormatException: Level must contain at least one Palette file!
   at SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 679
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by Clownacy** [comment]
Your wrote the wrong filename in your INI file: `art/layout/HPZ.kps` should be `art/layout/HPZ.kos`.
