### ISSUE TITLE
Odd behaviour when duplicating tiles

### ISSUE THREAD

**Issue by Pacguy64** [sonicretro/SonLVL#22]
When I select a tile and right click it to duplicate it, the tile that is next to it (the one that has a higher index number) is duplicated instead. Furthermore, if I attempt to duplicate the last level tile, I get this error, presumably due to the previous issue and the fact that their is no "next tile".

Program: SonLVL
Build Date: 11/25/2017 19:39:37
OS Version: Microsoft Windows NT 6.2.9200.0
Log:
Operating system: Microsoft Windows NT 6.2.9200.0
Opening INI file "C:\Users\Kain\Documents\disassemblies\Sonic 2 cd edition\SonLVL INI Files\SonLVL.ini"...
Game type is S2.
Loading Emerald Hill Zone Future Bad Act 1...
Loading 128x128 chunks from file "../mappings/128x128/EHZ_FUTURE_BAD.bin", using compression Kosinski...
Loading 16x16 blocks from file "../mappings/16x16/EHZ_FUTURE_BAD.bin", using compression Kosinski...
Loading palette file "../art/palettes/SonicAndTails.bin"...
Source: 0 Destination: 0 Length: 16
Loading 8x8 tiles from file "../art/kosinski/EHZ_FUTURE_BAD.bin", using compression Kosinski...
Loading palette file "../art/palettes/EHZFB.bin"...
Source: 0 Destination: 16 Length: 48
Loading layout from file "../level/layout_future_bad/EHZ_1.bin", using compression Kosinski...
Loading layout from file "../level/layout_future_bad/EHZ_2.bin", using compression Kosinski...
Loading object definition file "obj.ini".
Loading object definition file "objEHZ.ini".
Loading ObjectDefinition type S2ObjectDefinitions.Common.PathSwapper from "Common\PathSwapper.cs"...
Loading type from cached assembly "dllcache\S2ObjectDefinitions.Common.PathSwapper.dll"...
Loading ObjectDefinition type S2ObjectDefinitions.Common.InvisibleBlock from "Common\InvisibleBlock.cs"...
Loading type from cached assembly "dllcache\S2ObjectDefinitions.Common.InvisibleBlock.dll"...
Loading ObjectDefinition type S2ObjectDefinitions.EHZ.TwistingPathway from "EHZ\TwistingPathway.cs"...
Loading type from cached assembly "dllcache\S2ObjectDefinitions.EHZ.TwistingPathway.dll"...
Loading ObjectDefinition type S2ObjectDefinitions.EHZ.Bridge from "EHZ\Bridge.cs"...
Loading type from cached assembly "dllcache\S2ObjectDefinitions.EHZ.Bridge.dll"...
Loading type from cached assembly "dllcache\S2ObjectDefinitions.Common.Spikes.dll"...
Loading start position "Level Start" from file "../startpos/EHZ_1.bin"...
Loading objects from file "../level/objects_future_bad/EHZ_1.bin", using compression Uncompressed...
Loading rings from file "../level/rings_future_bad/EHZ_1.bin", using compression Uncompressed...
Drawing block bitmaps...
Drawing chunk bitmaps...
Load completed.
System.NullReferenceException: Object reference not set to an instance of an object.
   at SonicRetro.SonLVL.GUI.MainForm.duplicateTilesToolStripMenuItem_Click(Object sender, EventArgs e) in E:\AutoBuild\SonLVL\SonLVL\MainForm.cs:line 5118
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
System.NullReferenceException: Object reference not set to an instance of an object.
   at SonicRetro.SonLVL.GUI.MainForm.duplicateTilesToolStripMenuItem_Click(Object sender, EventArgs e) in E:\AutoBuild\SonLVL\SonLVL\MainForm.cs:line 5118
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
System.NullReferenceException: Object reference not set to an instance of an object.
   at SonicRetro.SonLVL.GUI.MainForm.duplicateTilesToolStripMenuItem_Click(Object sender, EventArgs e) in E:\AutoBuild\SonLVL\SonLVL\MainForm.cs:line 5118
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
System.NullReferenceException: Object reference not set to an instance of an object.
   at SonicRetro.SonLVL.GUI.MainForm.duplicateTilesToolStripMenuItem_Click(Object sender, EventArgs e) in E:\AutoBuild\SonLVL\SonLVL\MainForm.cs:line 5118
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by MainMemory** [comment]
I love off by one errors.
