### ISSUE TITLE
the level converter is not working

### ISSUE THREAD

**Issue by chriscatwhovian** [sonicretro/SonLVL#30]
Program: LevelConverter
Build Date: 02/21/2018 23:28:54
OS Version: Microsoft Windows NT 6.2.9200.0
Log:
Opening INI file "C:\Users\henry\Downloads\Sonic Maker\s1disasm-master\Sonic 1 2005 INIs\SonLVL.ini"...
Game type is S1.
Loading Green Hill Zone Act 1...
Loading palette file "../pallet/sonic.bin"...
Source: 0 Destination: 0 Length: 16
Loading 256x256 chunks from file "../map256/GHZ.bin", using compression Kosinski...
8x8 tile file "../artnem/8x8ghz1.bin" not found.
8x8 tile file "../artnem/8x8ghz2.bin" not found.
Loading FG layout from file "../levels/ghz1.bin", using compression Uncompressed...
Loading BG layout from file "../levels/ghzbg.bin", using compression Uncompressed...
Loading FG layout from file "../levels/ghz2.bin", using compression Uncompressed...
Loading FG layout from file "../levels/ghz3.bin", using compression Uncompressed...
Loading FG layout from file "../levels/ending.bin", using compression Uncompressed...
Loading 16x16 blocks from file "../map16/GHZ.bin", using compression Enigma...
System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
   at SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() in E:\AutoBuild\SonLVL\SonLVLAPI\LevelData.cs:line 542
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
   at System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions)
   at System.Threading.Tasks.Parallel.Invoke(Action[] actions)
   at SonicRetro.SonLVL.API.LevelData.LoadLevel(String levelname, Boolean loadGraphics) in E:\AutoBuild\SonLVL\SonLVLAPI\LevelData.cs:line 157
   at SonicRetro.SonLVL.LevelConverter.MainForm.ConvertLevel() in E:\AutoBuild\SonLVL\LevelConverter\MainForm.cs:line 141
   at SonicRetro.SonLVL.LevelConverter.MainForm.button1_Click(Object sender, EventArgs e) in E:\AutoBuild\SonLVL\LevelConverter\MainForm.cs:line 107
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
---> (Inner Exception #0) System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
File name: '../pallet/sonic.bin'
   at SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() in E:\AutoBuild\SonLVL\SonLVLAPI\LevelData.cs:line 542
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by MainMemory** [comment]
http://info.sonicretro.org/SCHG_How-to:Set_Up_SonLVL
