### ISSUE TITLE
Sonlvl will load zone definitions with no layout, but will crash when saving

### ISSUE THREAD

**Issue by Pacguy64** [sonicretro/SonLVL#31]
I occasionally use SonLVL just as another option to edit artwork, because I've gotten so used to it. Obviously, this isn't what it was made for though. Here's the relevant portion of the ini file for reference:

[OtherJunk\\Credits Background]
tilecmp=Nemesis
tiles=../NEWSEGASCREEN/SEGAARTNEM.bin
blocks=../mappings/Temporary/16x16/splashscreen.bin
chunks=../mappings/Temporary/128x128/splashscreen.bin
palette=../art/palettes/SonicAndTails.bin:0:0:16|../NEWSEGASCREEN/SEGAPAL.bin:0:16:48

Program: SonLVL
Build Date: 02/24/2018 20:58:19
OS Version: Microsoft Windows NT 6.2.9200.0
Log:
Operating system: Microsoft Windows NT 6.2.9200.0
Opening INI file "C:\Users\Kain\Documents\disassemblies\Sonic2CDremix\SonLVL INI Files\SonLVL.ini"...
Game type is S2.
Opening INI file "C:\Users\Kain\Documents\disassemblies\Sonic2CDremix\SonLVL INI Files\SonLVL.ini"...
Game type is S2.
Loading Credits Background...
Loading 8x8 tiles from file "../NEWSEGASCREEN/SEGAARTNEM.bin", using compression Nemesis...
128x128 chunk file "../mappings/Temporary/128x128/splashscreen.bin" not found.
16x16 block file "../mappings/Temporary/16x16/splashscreen.bin" not found.
Loading palette file "../art/palettes/SonicAndTails.bin"...
Source: 0 Destination: 0 Length: 16
Loading palette file "../NEWSEGASCREEN/SEGAPAL.bin"...
Source: 0 Destination: 16 Length: 48
Layout file "" not found.
Loading object definition file "obj.ini".
Loading object definition file "obj.ini".
Loading ObjectDefinition type S2ObjectDefinitions.Common.PathSwapper from "Common\PathSwapper.cs"...
Loading ObjectDefinition type S2ObjectDefinitions.Common.InvisibleBlock from "Common\InvisibleBlock.cs"...
Loading type from cached assembly "dllcache\S2ObjectDefinitions.Common.InvisibleBlock.dll"...
Loading type from cached assembly "dllcache\S2ObjectDefinitions.Common.PathSwapper.dll"...
Loading type from cached assembly "dllcache\S2ObjectDefinitions.Common.Spikes.dll"...
Drawing block bitmaps...
Drawing chunk bitmaps...
Load completed.
Saving Credits Background...
Unable to write file "" with compression Kosinski:
System.AggregateException: One or more errors occurred. ---> System.ArgumentNullException: Path cannot be null.
Parameter name: path
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at SonicRetro.SonLVL.API.Compression.Compress(Byte[] file, String destination, CompressionType cmp) in E:\AutoBuild\SonLVL\SonLVLAPI\Compression.cs:line 110
   at SonicRetro.SonLVL.API.LayoutFormatCombined.WriteLayout(LayoutData layout, CompressionType compression, String filename) in E:\AutoBuild\SonLVL\SonLVLAPI\LayoutFormat.cs:line 77
   at SonicRetro.SonLVL.API.LevelData.SaveLevelLayout() in E:\AutoBuild\SonLVL\SonLVLAPI\LevelData.cs:line 906
   at System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.<Invoke>b__0()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions)
   at SonicRetro.SonLVL.API.LevelData.SaveLevel() in E:\AutoBuild\SonLVL\SonLVLAPI\LevelData.cs:line 789
   at SonicRetro.SonLVL.GUI.MainForm.buildAndRunToolStripMenuItem_Click(Object sender, EventArgs e) in E:\AutoBuild\SonLVL\SonLVL\MainForm.cs:line 845
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
---> (Inner Exception #0) System.ArgumentNullException: Path cannot be null.
Parameter name: path
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at SonicRetro.SonLVL.API.Compression.Compress(Byte[] file, String destination, CompressionType cmp) in E:\AutoBuild\SonLVL\SonLVLAPI\Compression.cs:line 110
   at SonicRetro.SonLVL.API.LayoutFormatCombined.WriteLayout(LayoutData layout, CompressionType compression, String filename) in E:\AutoBuild\SonLVL\SonLVLAPI\LayoutFormat.cs:line 77
   at SonicRetro.SonLVL.API.LevelData.SaveLevelLayout() in E:\AutoBuild\SonLVL\SonLVLAPI\LevelData.cs:line 906
   at System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.<Invoke>b__0()<---

Saving Credits Background...
Unable to write file "" with compression Kosinski:
System.AggregateException: One or more errors occurred. ---> System.ArgumentNullException: Path cannot be null.
Parameter name: path
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at SonicRetro.SonLVL.API.Compression.Compress(Byte[] file, String destination, CompressionType cmp) in E:\AutoBuild\SonLVL\SonLVLAPI\Compression.cs:line 110
   at SonicRetro.SonLVL.API.LayoutFormatCombined.WriteLayout(LayoutData layout, CompressionType compression, String filename) in E:\AutoBuild\SonLVL\SonLVLAPI\LayoutFormat.cs:line 77
   at SonicRetro.SonLVL.API.LevelData.SaveLevelLayout() in E:\AutoBuild\SonLVL\SonLVLAPI\LevelData.cs:line 906
   at System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.<Invoke>b__0()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions)
   at SonicRetro.SonLVL.API.LevelData.SaveLevel() in E:\AutoBuild\SonLVL\SonLVLAPI\LevelData.cs:line 789
   at SonicRetro.SonLVL.GUI.MainForm.buildAndRunToolStripMenuItem_Click(Object sender, EventArgs e) in E:\AutoBuild\SonLVL\SonLVL\MainForm.cs:line 845
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
---> (Inner Exception #0) System.ArgumentNullException: Path cannot be null.
Parameter name: path
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at SonicRetro.SonLVL.API.Compression.Compress(Byte[] file, String destination, CompressionType cmp) in E:\AutoBuild\SonLVL\SonLVLAPI\Compression.cs:line 110
   at SonicRetro.SonLVL.API.LayoutFormatCombined.WriteLayout(LayoutData layout, CompressionType compression, String filename) in E:\AutoBuild\SonLVL\SonLVLAPI\LayoutFormat.cs:line 77
   at SonicRetro.SonLVL.API.LevelData.SaveLevelLayout() in E:\AutoBuild\SonLVL\SonLVLAPI\LevelData.cs:line 906
   at System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.<Invoke>b__0()<---

Saving Credits Background...
Unable to write file "" with compression Kosinski:
System.AggregateException: One or more errors occurred. ---> System.ArgumentNullException: Path cannot be null.
Parameter name: path
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at SonicRetro.SonLVL.API.Compression.Compress(Byte[] file, String destination, CompressionType cmp) in E:\AutoBuild\SonLVL\SonLVLAPI\Compression.cs:line 110
   at SonicRetro.SonLVL.API.LayoutFormatCombined.WriteLayout(LayoutData layout, CompressionType compression, String filename) in E:\AutoBuild\SonLVL\SonLVLAPI\LayoutFormat.cs:line 77
   at SonicRetro.SonLVL.API.LevelData.SaveLevelLayout() in E:\AutoBuild\SonLVL\SonLVLAPI\LevelData.cs:line 906
   at System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.<Invoke>b__0()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions)
   at SonicRetro.SonLVL.API.LevelData.SaveLevel() in E:\AutoBuild\SonLVL\SonLVLAPI\LevelData.cs:line 789
   at SonicRetro.SonLVL.GUI.MainForm.saveToolStripMenuItem_Click(Object sender, EventArgs e) in E:\AutoBuild\SonLVL\SonLVL\MainForm.cs:line 839
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
---> (Inner Exception #0) System.ArgumentNullException: Path cannot be null.
Parameter name: path
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at SonicRetro.SonLVL.API.Compression.Compress(Byte[] file, String destination, CompressionType cmp) in E:\AutoBuild\SonLVL\SonLVLAPI\Compression.cs:line 110
   at SonicRetro.SonLVL.API.LayoutFormatCombined.WriteLayout(LayoutData layout, CompressionType compression, String filename) in E:\AutoBuild\SonLVL\SonLVLAPI\LayoutFormat.cs:line 77
   at SonicRetro.SonLVL.API.LevelData.SaveLevelLayout() in E:\AutoBuild\SonLVL\SonLVLAPI\LevelData.cs:line 906
   at System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.<Invoke>b__0()<---

Saving Credits Background...
Unable to write file "" with compression Kosinski:
System.AggregateException: One or more errors occurred. ---> System.ArgumentNullException: Path cannot be null.
Parameter name: path
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at SonicRetro.SonLVL.API.Compression.Compress(Byte[] file, String destination, CompressionType cmp) in E:\AutoBuild\SonLVL\SonLVLAPI\Compression.cs:line 110
   at SonicRetro.SonLVL.API.LayoutFormatCombined.WriteLayout(LayoutData layout, CompressionType compression, String filename) in E:\AutoBuild\SonLVL\SonLVLAPI\LayoutFormat.cs:line 77
   at SonicRetro.SonLVL.API.LevelData.SaveLevelLayout() in E:\AutoBuild\SonLVL\SonLVLAPI\LevelData.cs:line 906
   at System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.<Invoke>b__0()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions)
   at SonicRetro.SonLVL.API.LevelData.SaveLevel() in E:\AutoBuild\SonLVL\SonLVLAPI\LevelData.cs:line 789
   at SonicRetro.SonLVL.GUI.MainForm.MainForm_FormClosing(Object sender, FormClosingEventArgs e) in E:\AutoBuild\SonLVL\SonLVL\MainForm.cs:line 330
   at System.Windows.Forms.Form.OnFormClosing(FormClosingEventArgs e)
   at System.Windows.Forms.Form.WmClose(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
---> (Inner Exception #0) System.ArgumentNullException: Path cannot be null.
Parameter name: path
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at SonicRetro.SonLVL.API.Compression.Compress(Byte[] file, String destination, CompressionType cmp) in E:\AutoBuild\SonLVL\SonLVLAPI\Compression.cs:line 110
   at SonicRetro.SonLVL.API.LayoutFormatCombined.WriteLayout(LayoutData layout, CompressionType compression, String filename) in E:\AutoBuild\SonLVL\SonLVLAPI\LayoutFormat.cs:line 77
   at SonicRetro.SonLVL.API.LevelData.SaveLevelLayout() in E:\AutoBuild\SonLVL\SonLVLAPI\LevelData.cs:line 906
   at System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.<Invoke>b__0()<---

**Comment by MainMemory** [comment]
Um. I don't know about this. It's a very nonstandard usage of the program. Maybe I should make a plane mappings editor.

Also, if you really want to use SonLVL for general art editing, you could just make a dummy layout file.

**Comment by Pacguy64** [comment]
Yeah, I realize that a dummy layout file could fix it. The fact that SonLVL is even able to load a level without the definitions is strange though; perhaps an error should be intentionally raised in this case, to match behavior with other errors involving incomplete/broken ini definitions.
