### ISSUE TITLE
Occasional crash when loading a level

### ISSUE THREAD

**Issue by Pacguy64** [sonicretro/SonLVL#39]
I often leave Sonlvl running for long periods of time, with or without a level loaded. Doing this seems to increase the odds of Sonlvl spitting out an error instead of actually loading the level, though. I'm not 100% sure how to reproduce this, but once it happens, I'm unable to switch levels until I close and restart Sonlvl.

Program: SonLVL
Build Date: 03/30/2018 21:08:43
OS Version: Microsoft Windows NT 6.2.9200.0
Log:
Operating system: Microsoft Windows NT 6.2.9200.0
Opening INI file "C:\Users\Kain\Documents\disassemblies\Sonic2CDremix\SonLVL INI Files\SonLVL.ini"...
Game type is S2.
System.ComponentModel.Win32Exception (0x80004005): The operation was canceled by the user
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at SonicRetro.SonLVL.GUI.MainForm.buildAndRunToolStripMenuItem_Click(Object sender, EventArgs e) in E:\AutoBuild\SonLVL\SonLVL\MainForm.cs:line 850
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
Loading Chemical Plant Zone Act 2...
Loading 16x16 blocks from file "../mappings/16x16/CPZ_DEZ.bin", using compression Kosinski...
Loading 128x128 chunks from file "../mappings/128x128/CPZ_DEZ.bin", using compression Kosinski...
Loading palette file "../art/palettes/SonicAndTails.bin"...
Source: 0 Destination: 0 Length: 16
Loading palette file "../art/palettes/CPZ.bin"...
Source: 0 Destination: 16 Length: 48
Loading palette file "../art/palettes/CPZ underwater.bin"...
Source: 0 Destination: 0 Length: 64
Loading layout from file "../level/layout/CPZ_2.bin", using compression Kosinski...
Loading layout from file "../level/layout/CPZ_1.bin", using compression Kosinski...
Loading object definition file "obj.ini".
Loading object definition file "objCPZ.ini".
Loading ObjectDefinition type S2ObjectDefinitions.Common.PathSwapper from "Common\PathSwapper.cs"...
Compiling code file...
Loading ObjectDefinition type S2ObjectDefinitions.Common.InvisibleBlock from "Common\InvisibleBlock.cs"...
Compiling code file...
Building code file...
Compiling code file...
System.AggregateException: One or more errors occurred. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Kain\Google Drive\Sonlvl+genesis emulators\sonlvl\bin\roslyn\csc.exe'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Microsoft.CodeDom.Providers.DotNetCompilerPlatform.Compiler.get_CompilerName()
   at Microsoft.CodeDom.Providers.DotNetCompilerPlatform.Compiler.FromFileBatch(CompilerParameters options, String[] fileNames)
   at Microsoft.CodeDom.Providers.DotNetCompilerPlatform.Compiler.CompileAssemblyFromFileBatch(CompilerParameters options, String[] fileNames)
   at System.CodeDom.Compiler.CodeDomProvider.CompileAssemblyFromFile(CompilerParameters options, String[] fileNames)
   at SonicRetro.SonLVL.API.LevelData.<>c__DisplayClass98_0.<InitObjectDefinitions>b__0(KeyValuePair`2 group) in E:\AutoBuild\SonLVL\SonLVLAPI\LevelData.cs:line 1363
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at SonicRetro.SonLVL.API.LevelData.InitObjectDefinitions() in E:\AutoBuild\SonLVL\SonLVLAPI\LevelData.cs:line 1314
   at SonicRetro.SonLVL.API.LevelData.LoadLevel(String levelname, Boolean loadGraphics) in E:\AutoBuild\SonLVL\SonLVLAPI\LevelData.cs:line 271
   at SonicRetro.SonLVL.GUI.MainForm.backgroundLevelLoader_DoWork(Object sender, DoWorkEventArgs e) in E:\AutoBuild\SonLVL\SonLVL\MainForm.cs:line 556
---> (Inner Exception #0) System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Kain\Google Drive\Sonlvl+genesis emulators\sonlvl\bin\roslyn\csc.exe'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Microsoft.CodeDom.Providers.DotNetCompilerPlatform.Compiler.get_CompilerName()
   at Microsoft.CodeDom.Providers.DotNetCompilerPlatform.Compiler.FromFileBatch(CompilerParameters options, String[] fileNames)
   at Microsoft.CodeDom.Providers.DotNetCompilerPlatform.Compiler.CompileAssemblyFromFileBatch(CompilerParameters options, String[] fileNames)
   at System.CodeDom.Compiler.CodeDomProvider.CompileAssemblyFromFile(CompilerParameters options, String[] fileNames)
   at SonicRetro.SonLVL.API.LevelData.<>c__DisplayClass98_0.<InitObjectDefinitions>b__0(KeyValuePair`2 group) in E:\AutoBuild\SonLVL\SonLVLAPI\LevelData.cs:line 1363
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

---> (Inner Exception #1) System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Kain\Google Drive\Sonlvl+genesis emulators\sonlvl\bin\roslyn\csc.exe'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Microsoft.CodeDom.Providers.DotNetCompilerPlatform.Compiler.get_CompilerName()
   at Microsoft.CodeDom.Providers.DotNetCompilerPlatform.Compiler.FromFileBatch(CompilerParameters options, String[] fileNames)
   at Microsoft.CodeDom.Providers.DotNetCompilerPlatform.Compiler.CompileAssemblyFromFileBatch(CompilerParameters options, String[] fileNames)
   at System.CodeDom.Compiler.CodeDomProvider.CompileAssemblyFromFile(CompilerParameters options, String[] fileNames)
   at SonicRetro.SonLVL.API.LevelData.<>c__DisplayClass98_0.<InitObjectDefinitions>b__0(KeyValuePair`2 group) in E:\AutoBuild\SonLVL\SonLVLAPI\LevelData.cs:line 1363
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

---> (Inner Exception #2) System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Kain\Google Drive\Sonlvl+genesis emulators\sonlvl\bin\roslyn\csc.exe'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Microsoft.CodeDom.Providers.DotNetCompilerPlatform.Compiler.get_CompilerName()
   at Microsoft.CodeDom.Providers.DotNetCompilerPlatform.Compiler.FromFileBatch(CompilerParameters options, String[] fileNames)
   at Microsoft.CodeDom.Providers.DotNetCompilerPlatform.Compiler.FromSourceBatch(CompilerParameters options, String[] sources)
   at Microsoft.CodeDom.Providers.DotNetCompilerPlatform.Compiler.CompileAssemblyFromDomBatch(CompilerParameters options, CodeCompileUnit[] compilationUnits)
   at System.CodeDom.Compiler.CodeDomProvider.CompileAssemblyFromDom(CompilerParameters options, CodeCompileUnit[] compilationUnits)
   at SonicRetro.SonLVL.API.XMLObjectDefinition.Init(ObjectData data) in E:\AutoBuild\SonLVL\SonLVLAPI\ObjectDefinition.cs:line 923
   at SonicRetro.SonLVL.API.LevelData.<>c__DisplayClass98_0.<InitObjectDefinitions>b__0(KeyValuePair`2 group) in E:\AutoBuild\SonLVL\SonLVLAPI\LevelData.cs:line 1387
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

**Comment by MainMemory** [comment]
Okay, this error is with a broken build of SonLVL from earlier today, so it doesn't mean anything. If you can get me a log with the current build, then we might have something.

**Comment by Pacguy64** [comment]
Darn! I'll be sure to get another log if this pops up again!

**Comment by Pacguy64** [comment]
I now remember why I was dragging my feet on reporting this... It crashes to windows, without opening the report window! I'm using windows 10, if that helps...

**Comment by Pacguy64** [comment]
I just ran into the issue again, and now remember why I failed to report it; the usual report window doesn't come up, because SonLVL suffers a windows crash! Thus, there's no log to dissect...

The crash definitely occurs when loading the new level; I've had it happen while switching between open levels, and choosing the pop up option to save my work. The old level gets saved properly, and then SonLVL crashes on the next levels loading screen. I'm using Windows 10, if thats' any help.

I've started running into this pretty regularly when switching between levels in quick succession, so I may be able to provide more info if you tell me what to look for.

**Comment by MainMemory** [comment]
Well then, I guess the only thing I can do is run SonLVL with a debugger attached and hope it crashes.

**Comment by Pacguy64** [comment]
Crash still occurs on the current release. Feel free to send me a debugger version, I'd be happy to no end to see this crash fixed.

**Comment by MainMemory** [comment]
That's not how it works. You would need to install Visual Studio and run SonLVL through its debugger.

**Comment by Pacguy64** [comment]
Oh. That's a bit more complicated then I would have hoped for. I'll look into it when I have more spare time.
