### ISSUE TITLE
Crash when loading Labyrinth, Star Light and Scrap Brain when using Mercury's ReadySonic

### ISSUE THREAD

**Issue by NoahCamp97** [sonicretro/SonLVL#41]
Mercury's ReadySonic is a project that adds certain features built in to the Sonic 1 Git disassembly.  I use the Git SonLVL INIs, specifically the Rev01.  Back in 2014 I believe I recall using SonLVL with this project without any problems.  Green Hill, Marble, and Spring Yard load perfectly, but any other level poses this error:

Program: SonLVL
Build Date: 04/22/2018 18:47:54
OS Version: Microsoft Windows NT 6.2.9200.0
Log:
Operating system: Microsoft Windows NT 6.2.9200.0
Opening INI file "C:\Users\roxur\Desktop\Gaming\Emulators\Fusion364\Sonic Hacks\Sonic 1 HD\Sonic 1 Git INIs\SonLVL.rev01.ini"...
Game type is S1.
Loading Labyrinth Zone Act 1...
Loading 16x16 blocks from file "../map16/LZ.bin", using compression Enigma...
Loading 256x256 chunks from file "../map256/LZ.bin", using compression Kosinski...
Loading 8x8 tiles from file "../artnem/8x8 - LZ.bin", using compression Nemesis...
Loading FG layout from file "../levels/lz1.bin", using compression Uncompressed...
Loading BG layout from file "../levels/lzbg.bin", using compression Uncompressed...
Loading FG layout from file "../levels/lz2.bin", using compression Uncompressed...
Loading palette file "../palette/Sonic.bin"...
Source: 0 Destination: 0 Length: 16
Loading palette file "../palette/Labyrinth Zone.bin"...
Source: 0 Destination: 16 Length: 48
Loading palette file "../palette/Labyrinth Zone Underwater.bin"...
Source: 0 Destination: 0 Length: 64
Loading FG layout from file "../levels/lz3.bin", using compression Uncompressed...
Loading FG layout from file "../levels/sbz3.bin", using compression Uncompressed...
Loading object definition file "obj.ini".
Loading object definition file "obj.rev01.ini".
Loading object definition file "objLZ.ini".
Loading ObjectDefinition type S1ObjectDefinitions.Common.Ring from "Common\Ring.cs"...
Loading type from cached assembly "dllcache\S1ObjectDefinitions.Common.Ring.dll"...
Loading ObjectDefinition type S1ObjectDefinitions.Common.InvisibleBlock from "Common\InvisibleBlock.cs"...
Loading type from cached assembly "dllcache\S1ObjectDefinitions.Common.InvisibleBlock.dll"...
Loading type from cached assembly "dllcache\S1ObjectDefinitions.LZ.Bubbles.dll"...
System.AggregateException: One or more errors occurred. ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at SonicRetro.SonLVL.API.MappingsTile..ctor(Byte[] file, Int32 address, EngineVersion version) in E:\AutoBuild\SonLVL\SonLVLAPI\DataTypes.cs:line 1256
   at SonicRetro.SonLVL.API.MappingsFrame..ctor(Byte[] file, Int32 address, EngineVersion version, String name) in E:\AutoBuild\SonLVL\SonLVLAPI\DataTypes.cs:line 1386
   at SonicRetro.SonLVL.API.MappingsFrame.Load(Byte[] file, EngineVersion version, Dictionary`2 labels) in E:\AutoBuild\SonLVL\SonLVLAPI\DataTypes.cs:line 1359
   at SonicRetro.SonLVL.API.ObjectHelper.MapToBmp(Byte[] artfile, Byte[] mapfile, Int32 frame, Int32 startpal, EngineVersion version) in E:\AutoBuild\SonLVL\SonLVLAPI\ObjectHelper.cs:line 15
   at SonicRetro.SonLVL.API.ObjectHelper.MapASMToBmp(Byte[] artfile, String mapfileloc, Int32 frame, Int32 startpal, EngineVersion version) in E:\AutoBuild\SonLVL\SonLVLAPI\ObjectHelper.cs:line 28
   at SonicRetro.SonLVL.API.XMLObjectDefinition.Init(ObjectData data) in E:\AutoBuild\SonLVL\SonLVLAPI\ObjectDefinition.cs:line 699
   at SonicRetro.SonLVL.API.LevelData.<>c__DisplayClass97_0.<InitObjectDefinitions>b__0(KeyValuePair`2 group) in E:\AutoBuild\SonLVL\SonLVLAPI\LevelData.cs:line 1428
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at SonicRetro.SonLVL.API.LevelData.InitObjectDefinitions() in E:\AutoBuild\SonLVL\SonLVLAPI\LevelData.cs:line 1355
   at SonicRetro.SonLVL.API.LevelData.LoadLevel(String levelname, Boolean loadGraphics) in E:\AutoBuild\SonLVL\SonLVLAPI\LevelData.cs:line 293
   at SonicRetro.SonLVL.GUI.MainForm.backgroundLevelLoader_DoWork(Object sender, DoWorkEventArgs e) in E:\AutoBuild\SonLVL\SonLVL\MainForm.cs:line 560
---> (Inner Exception #0) System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at SonicRetro.SonLVL.API.MappingsTile..ctor(Byte[] file, Int32 address, EngineVersion version) in E:\AutoBuild\SonLVL\SonLVLAPI\DataTypes.cs:line 1256
   at SonicRetro.SonLVL.API.MappingsFrame..ctor(Byte[] file, Int32 address, EngineVersion version, String name) in E:\AutoBuild\SonLVL\SonLVLAPI\DataTypes.cs:line 1386
   at SonicRetro.SonLVL.API.MappingsFrame.Load(Byte[] file, EngineVersion version, Dictionary`2 labels) in E:\AutoBuild\SonLVL\SonLVLAPI\DataTypes.cs:line 1359
   at SonicRetro.SonLVL.API.ObjectHelper.MapToBmp(Byte[] artfile, Byte[] mapfile, Int32 frame, Int32 startpal, EngineVersion version) in E:\AutoBuild\SonLVL\SonLVLAPI\ObjectHelper.cs:line 15
   at SonicRetro.SonLVL.API.ObjectHelper.MapASMToBmp(Byte[] artfile, String mapfileloc, Int32 frame, Int32 startpal, EngineVersion version) in E:\AutoBuild\SonLVL\SonLVLAPI\ObjectHelper.cs:line 28
   at SonicRetro.SonLVL.API.XMLObjectDefinition.Init(ObjectData data) in E:\AutoBuild\SonLVL\SonLVLAPI\ObjectDefinition.cs:line 699
   at SonicRetro.SonLVL.API.LevelData.<>c__DisplayClass97_0.<InitObjectDefinitions>b__0(KeyValuePair`2 group) in E:\AutoBuild\SonLVL\SonLVLAPI\LevelData.cs:line 1428
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

Loading Labyrinth Zone Act 2...
Loading 16x16 blocks from file "../map16/LZ.bin", using compression Enigma...
Loading 256x256 chunks from file "../map256/LZ.bin", using compression Kosinski...
Loading FG layout from file "../levels/lz2.bin", using compression Uncompressed...
Loading palette file "../palette/Sonic.bin"...
Source: 0 Destination: 0 Length: 16
Loading BG layout from file "../levels/lzbg.bin", using compression Uncompressed...
Loading 8x8 tiles from file "../artnem/8x8 - LZ.bin", using compression Nemesis...
Loading palette file "../palette/Labyrinth Zone.bin"...
Source: 0 Destination: 16 Length: 48
Loading palette file "../palette/Labyrinth Zone Underwater.bin"...
Source: 0 Destination: 0 Length: 64
Loading FG layout from file "../levels/lz1.bin", using compression Uncompressed...
Loading FG layout from file "../levels/lz3.bin", using compression Uncompressed...
Loading FG layout from file "../levels/sbz3.bin", using compression Uncompressed...
Loading object definition file "obj.ini".
Loading object definition file "obj.rev01.ini".
Loading object definition file "objLZ.ini".
Loading ObjectDefinition type S1ObjectDefinitions.Common.Ring from "Common\Ring.cs"...
Loading type from cached assembly "dllcache\S1ObjectDefinitions.Common.Ring.dll"...
Loading ObjectDefinition type S1ObjectDefinitions.Common.InvisibleBlock from "Common\InvisibleBlock.cs"...
Loading type from cached assembly "dllcache\S1ObjectDefinitions.Common.InvisibleBlock.dll"...
Loading ObjectDefinition type S1ObjectDefinitions.LZ.Spikeball from "LZ\Spikeball.cs"...
Loading type from cached assembly "dllcache\S1ObjectDefinitions.LZ.Spikeball.dll"...
Loading type from cached assembly "dllcache\S1ObjectDefinitions.LZ.Bubbles.dll"...
System.AggregateException: One or more errors occurred. ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at SonicRetro.SonLVL.API.MappingsTile..ctor(Byte[] file, Int32 address, EngineVersion version) in E:\AutoBuild\SonLVL\SonLVLAPI\DataTypes.cs:line 1256
   at SonicRetro.SonLVL.API.MappingsFrame..ctor(Byte[] file, Int32 address, EngineVersion version, String name) in E:\AutoBuild\SonLVL\SonLVLAPI\DataTypes.cs:line 1386
   at SonicRetro.SonLVL.API.MappingsFrame.Load(Byte[] file, EngineVersion version, Dictionary`2 labels) in E:\AutoBuild\SonLVL\SonLVLAPI\DataTypes.cs:line 1359
   at SonicRetro.SonLVL.API.ObjectHelper.MapToBmp(Byte[] artfile, Byte[] mapfile, Int32 frame, Int32 startpal, EngineVersion version) in E:\AutoBuild\SonLVL\SonLVLAPI\ObjectHelper.cs:line 15
   at SonicRetro.SonLVL.API.ObjectHelper.MapASMToBmp(Byte[] artfile, String mapfileloc, Int32 frame, Int32 startpal, EngineVersion version) in E:\AutoBuild\SonLVL\SonLVLAPI\ObjectHelper.cs:line 28
   at SonicRetro.SonLVL.API.XMLObjectDefinition.Init(ObjectData data) in E:\AutoBuild\SonLVL\SonLVLAPI\ObjectDefinition.cs:line 699
   at SonicRetro.SonLVL.API.LevelData.<>c__DisplayClass97_0.<InitObjectDefinitions>b__0(KeyValuePair`2 group) in E:\AutoBuild\SonLVL\SonLVLAPI\LevelData.cs:line 1428
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at SonicRetro.SonLVL.API.LevelData.InitObjectDefinitions() in E:\AutoBuild\SonLVL\SonLVLAPI\LevelData.cs:line 1355
   at SonicRetro.SonLVL.API.LevelData.LoadLevel(String levelname, Boolean loadGraphics) in E:\AutoBuild\SonLVL\SonLVLAPI\LevelData.cs:line 293
   at SonicRetro.SonLVL.GUI.MainForm.backgroundLevelLoader_DoWork(Object sender, DoWorkEventArgs e) in E:\AutoBuild\SonLVL\SonLVL\MainForm.cs:line 560
---> (Inner Exception #0) System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at SonicRetro.SonLVL.API.MappingsTile..ctor(Byte[] file, Int32 address, EngineVersion version) in E:\AutoBuild\SonLVL\SonLVLAPI\DataTypes.cs:line 1256
   at SonicRetro.SonLVL.API.MappingsFrame..ctor(Byte[] file, Int32 address, EngineVersion version, String name) in E:\AutoBuild\SonLVL\SonLVLAPI\DataTypes.cs:line 1386
   at SonicRetro.SonLVL.API.MappingsFrame.Load(Byte[] file, EngineVersion version, Dictionary`2 labels) in E:\AutoBuild\SonLVL\SonLVLAPI\DataTypes.cs:line 1359
   at SonicRetro.SonLVL.API.ObjectHelper.MapToBmp(Byte[] artfile, Byte[] mapfile, Int32 frame, Int32 startpal, EngineVersion version) in E:\AutoBuild\SonLVL\SonLVLAPI\ObjectHelper.cs:line 15
   at SonicRetro.SonLVL.API.ObjectHelper.MapASMToBmp(Byte[] artfile, String mapfileloc, Int32 frame, Int32 startpal, EngineVersion version) in E:\AutoBuild\SonLVL\SonLVLAPI\ObjectHelper.cs:line 28
   at SonicRetro.SonLVL.API.XMLObjectDefinition.Init(ObjectData data) in E:\AutoBuild\SonLVL\SonLVLAPI\ObjectDefinition.cs:line 699
   at SonicRetro.SonLVL.API.LevelData.<>c__DisplayClass97_0.<InitObjectDefinitions>b__0(KeyValuePair`2 group) in E:\AutoBuild\SonLVL\SonLVLAPI\LevelData.cs:line 1428
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

**Comment by MainMemory** [comment]
http://sonicresearch.org/community/index.php?threads/sonlvl.2217/page-17#post-79208
