### ISSUE TITLE
LZ, SLZ, and SBZ not working.

### ISSUE THREAD

**Issue by CreeperKraken15** [sonicretro/SonLVL#48]
For some strange reason, on my *secret* Sonic the Hedgehog 1 hack (Using ReadySonic, by Mercury), Labyrinth, Star Light, and Scrap Brain won't work. Instead, it leaves me this error:
"Program: SonLVL
Build Date: 08/03/2018 21:34:09
OS Version: Microsoft Windows NT 6.2.9200.0
Log:
Operating system: Microsoft Windows NT 6.2.9200.0
Opening INI file "C:\Users\flaso\Downloads\ROM Hacks\Sonic 1 Fusion Edition\s1disasm-master\SonLVL INI Files\SonLVL.ini"...
Game type is S1.
Loading Star Light Zone Act 1...
Loading 16x16 blocks from file "../map16/SLZ.bin", using compression Enigma...
Loading 256x256 chunks from file "../map256/SLZ.bin", using compression Kosinski...
Loading 8x8 tiles from file "../artnem/8x8 - SLZ.bin", using compression Nemesis...
Loading FG layout from file "../levels/slz1.bin", using compression Uncompressed...
Loading BG layout from file "../levels/slzbg.bin", using compression Uncompressed...
Loading palette file "../palette/Sonic.bin"...
Source: 0 Destination: 0 Length: 16
Loading palette file "../palette/Star Light Zone.bin"...
Source: 0 Destination: 16 Length: 48
Loading FG layout from file "../levels/slz2.bin", using compression Uncompressed...
Loading FG layout from file "../levels/slz3.bin", using compression Uncompressed...
Loading object definition file "obj.ini".
Loading object definition file "objSLZ.ini".
Loading ObjectDefinition type S1ObjectDefinitions.Common.Ring from "Common\Ring.cs"...
Loading type from cached assembly "dllcache\S1ObjectDefinitions.Common.Ring.dll"...
Loading ObjectDefinition type S1ObjectDefinitions.Common.InvisibleBlock from "Common\InvisibleBlock.cs"...
Compiling code file...
Loading ObjectDefinition type S1ObjectDefinitions.SLZ.SwingingPlatform from "SLZ\SwingingPlatform.cs"...
Compiling code file...
Loading type from cached assembly "dllcache\S1ObjectDefinitions.SLZ.Elevator.dll"...
Compile failed.
Errors:
c:\Users\flaso\Downloads\ROM Hacks\Sonic 1 Fusion Edition\s1disasm-master\SonLVL INI Files\Common\InvisibleBlock.cs(60,29) : error CS0115: 'S1ObjectDefinitions.Common.InvisibleBlock.GetBounds(SonicRetro.SonLVL.API.ObjectEntry, System.Drawing.Point)': no suitable method found to override

Compile failed.
Errors:
c:\Users\flaso\Downloads\ROM Hacks\Sonic 1 Fusion Edition\s1disasm-master\SonLVL INI Files\SLZ\SwingingPlatform.cs(58,29) : error CS0115: 'S1ObjectDefinitions.SLZ.SwingingPlatform.GetBounds(SonicRetro.SonLVL.API.ObjectEntry, System.Drawing.Point)': no suitable method found to override

Loading objects from file "../objpos/slz1.bin", using compression Uncompressed...
Loading start position "Level Start" from file "../startpos/slz1.bin"...
Drawing block bitmaps...
Drawing chunk bitmaps...
Level loaded in 1.675515 second(s).
Load completed.
Saving Star Light Zone Act 1...
Saving Star Light Zone Act 1...
Loading Star Light Zone Act 1...
Loading 8x8 tiles from file "../artnem/8x8 - SLZ.bin", using compression Nemesis...
Loading 16x16 blocks from file "../map16/SLZ.bin", using compression Enigma...
Loading 256x256 chunks from file "../map256/SLZ.bin", using compression Kosinski...
Loading FG layout from file "../levels/slz1.bin", using compression Uncompressed...
Loading palette file "../palette/Sonic.bin"...
Source: 0 Destination: 0 Length: 16
Loading palette file "../palette/Star Light Zone.bin"...
Source: 0 Destination: 16 Length: 48
Loading BG layout from file "../levels/slzbg.bin", using compression Uncompressed...
Loading FG layout from file "../levels/slz2.bin", using compression Uncompressed...
Loading FG layout from file "../levels/slz3.bin", using compression Uncompressed...
Loading object definition file "obj.ini".
Loading object definition file "objSLZ.ini".
Loading ObjectDefinition type S1ObjectDefinitions.Common.Ring from "Common\Ring.cs"...
Loading type from cached assembly "dllcache\S1ObjectDefinitions.Common.Ring.dll"...
Loading ObjectDefinition type S1ObjectDefinitions.Common.InvisibleBlock from "Common\InvisibleBlock.cs"...
Compiling code file...
Loading ObjectDefinition type S1ObjectDefinitions.SLZ.SwingingPlatform from "SLZ\SwingingPlatform.cs"...
Compiling code file...
Loading type from cached assembly "dllcache\S1ObjectDefinitions.SLZ.Elevator.dll"...
Compile failed.
Errors:
c:\Users\flaso\Downloads\ROM Hacks\Sonic 1 Fusion Edition\s1disasm-master\SonLVL INI Files\Common\InvisibleBlock.cs(60,29) : error CS0115: 'S1ObjectDefinitions.Common.InvisibleBlock.GetBounds(SonicRetro.SonLVL.API.ObjectEntry, System.Drawing.Point)': no suitable method found to override

Compile failed.
Errors:
c:\Users\flaso\Downloads\ROM Hacks\Sonic 1 Fusion Edition\s1disasm-master\SonLVL INI Files\SLZ\SwingingPlatform.cs(58,29) : error CS0115: 'S1ObjectDefinitions.SLZ.SwingingPlatform.GetBounds(SonicRetro.SonLVL.API.ObjectEntry, System.Drawing.Point)': no suitable method found to override

Loading objects from file "../objpos/slz1.bin", using compression Uncompressed...
Loading start position "Level Start" from file "../startpos/slz1.bin"...
Drawing block bitmaps...
Drawing chunk bitmaps...
Level loaded in 0.7726718 second(s).
Load completed.
Saving Star Light Zone Act 1...
Saving Star Light Zone Act 1...
Saving Star Light Zone Act 1...
Opening INI file "C:\Users\flaso\Downloads\PA\ReadySonic 1.1 (source)\Sonic 1 Git INIs\SonLVL.ini"...
Game type is S1.
Loading Star Light Zone Act 1...
Loading 16x16 blocks from file "../map16/SLZ.bin", using compression Enigma...
Loading 256x256 chunks from file "../map256/SLZ.bin", using compression Kosinski...
Loading FG layout from file "../levels/slz1.bin", using compression Uncompressed...
Loading BG layout from file "../levels/slzbg.bin", using compression Uncompressed...
Loading palette file "../palette/Sonic.bin"...
Source: 0 Destination: 0 Length: 16
Loading palette file "../palette/Star Light Zone.bin"...
Source: 0 Destination: 16 Length: 48
Loading 8x8 tiles from file "../artnem/8x8 - SLZ.bin", using compression Nemesis...
Loading FG layout from file "../levels/slz2.bin", using compression Uncompressed...
Loading FG layout from file "../levels/slz3.bin", using compression Uncompressed...
Loading object definition file "obj.ini".
Loading object definition file "objSLZ.ini".
Loading ObjectDefinition type S1ObjectDefinitions.Common.Ring from "Common\Ring.cs"...
Loading type from cached assembly "dllcache\S1ObjectDefinitions.Common.Ring.dll"...
Loading ObjectDefinition type S1ObjectDefinitions.Common.InvisibleBlock from "Common\InvisibleBlock.cs"...
Loading type from cached assembly "dllcache\S1ObjectDefinitions.Common.InvisibleBlock.dll"...
Loading ObjectDefinition type S1ObjectDefinitions.SLZ.SwingingPlatform from "SLZ\SwingingPlatform.cs"...
Loading type from cached assembly "dllcache\S1ObjectDefinitions.SLZ.SwingingPlatform.dll"...
Loading type from cached assembly "dllcache\S1ObjectDefinitions.SLZ.Elevator.dll"...
System.AggregateException: One or more errors occurred. ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at SonicRetro.SonLVL.API.MappingsTile..ctor(Byte[] file, Int32 address, EngineVersion version) in E:\AutoBuild\SonLVL\SonLVLAPI\DataTypes.cs:line 1284
   at SonicRetro.SonLVL.API.MappingsFrame..ctor(Byte[] file, Int32 address, EngineVersion version, String name) in E:\AutoBuild\SonLVL\SonLVLAPI\DataTypes.cs:line 1414
   at SonicRetro.SonLVL.API.MappingsFrame.Load(Byte[] file, EngineVersion version, Dictionary`2 labels) in E:\AutoBuild\SonLVL\SonLVLAPI\DataTypes.cs:line 1387
   at SonicRetro.SonLVL.API.ObjectHelper.MapToBmp(Byte[] artfile, Byte[] mapfile, Int32 frame, Int32 startpal, Boolean priority, EngineVersion version) in E:\AutoBuild\SonLVL\SonLVLAPI\ObjectHelper.cs:line 10
   at SonicRetro.SonLVL.API.ObjectHelper.MapASMToBmp(Byte[] artfile, String mapfileloc, Int32 frame, Int32 startpal, Boolean priority, EngineVersion version) in E:\AutoBuild\SonLVL\SonLVLAPI\ObjectHelper.cs:line 18
   at SonicRetro.SonLVL.API.XMLObjectDefinition.Init(ObjectData data) in E:\AutoBuild\SonLVL\SonLVLAPI\ObjectDefinition.cs:line 710
   at SonicRetro.SonLVL.API.LevelData.<>c__DisplayClass100_0.<InitObjectDefinitions>b__0(KeyValuePair`2 group) in E:\AutoBuild\SonLVL\SonLVLAPI\LevelData.cs:line 1508
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at SonicRetro.SonLVL.API.LevelData.InitObjectDefinitions() in E:\AutoBuild\SonLVL\SonLVLAPI\LevelData.cs:line 1435
   at SonicRetro.SonLVL.API.LevelData.LoadLevel(String levelname, Boolean loadGraphics) in E:\AutoBuild\SonLVL\SonLVLAPI\LevelData.cs:line 304
   at SonicRetro.SonLVL.GUI.MainForm.backgroundLevelLoader_DoWork(Object sender, DoWorkEventArgs e) in E:\AutoBuild\SonLVL\SonLVL\MainForm.cs:line 561
---> (Inner Exception #0) System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at SonicRetro.SonLVL.API.MappingsTile..ctor(Byte[] file, Int32 address, EngineVersion version) in E:\AutoBuild\SonLVL\SonLVLAPI\DataTypes.cs:line 1284
   at SonicRetro.SonLVL.API.MappingsFrame..ctor(Byte[] file, Int32 address, EngineVersion version, String name) in E:\AutoBuild\SonLVL\SonLVLAPI\DataTypes.cs:line 1414
   at SonicRetro.SonLVL.API.MappingsFrame.Load(Byte[] file, EngineVersion version, Dictionary`2 labels) in E:\AutoBuild\SonLVL\SonLVLAPI\DataTypes.cs:line 1387
   at SonicRetro.SonLVL.API.ObjectHelper.MapToBmp(Byte[] artfile, Byte[] mapfile, Int32 frame, Int32 startpal, Boolean priority, EngineVersion version) in E:\AutoBuild\SonLVL\SonLVLAPI\ObjectHelper.cs:line 10
   at SonicRetro.SonLVL.API.ObjectHelper.MapASMToBmp(Byte[] artfile, String mapfileloc, Int32 frame, Int32 startpal, Boolean priority, EngineVersion version) in E:\AutoBuild\SonLVL\SonLVLAPI\ObjectHelper.cs:line 18
   at SonicRetro.SonLVL.API.XMLObjectDefinition.Init(ObjectData data) in E:\AutoBuild\SonLVL\SonLVLAPI\ObjectDefinition.cs:line 710
   at SonicRetro.SonLVL.API.LevelData.<>c__DisplayClass100_0.<InitObjectDefinitions>b__0(KeyValuePair`2 group) in E:\AutoBuild\SonLVL\SonLVLAPI\LevelData.cs:line 1508
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

Loading Green Hill Zone Act 3...
Loading FG layout from file "../levels/ghz3.bin", using compression Uncompressed...
Loading 256x256 chunks from file "../map256/GHZ.bin", using compression Kosinski...
Loading 8x8 tiles from file "../artnem/8x8 - GHZ1.bin", using compression Nemesis...
Loading 16x16 blocks from file "../map16/GHZ.bin", using compression Enigma...
Loading BG layout from file "../levels/ghzbg.bin", using compression Uncompressed...
Loading FG layout from file "../levels/ghz1.bin", using compression Uncompressed...
Loading palette file "../palette/Sonic.bin"...
Source: 0 Destination: 0 Length: 16
Loading FG layout from file "../levels/ghz2.bin", using compression Uncompressed...
Loading palette file "../palette/Green Hill Zone.bin"...
Source: 0 Destination: 16 Length: 48
Loading 8x8 tiles from file "../artnem/8x8 - GHZ2.bin", using compression Nemesis...
Loading FG layout from file "../levels/ending.bin", using compression Uncompressed...
Loading object definition file "obj.ini".
Loading object definition file "objGHZ.ini".
Loading ObjectDefinition type S1ObjectDefinitions.Common.Ring from "Common\Ring.cs"...
Loading type from cached assembly "dllcache\S1ObjectDefinitions.Common.Ring.dll"...
Loading ObjectDefinition type S1ObjectDefinitions.Common.InvisibleBlock from "Common\InvisibleBlock.cs"...
Loading type from cached assembly "dllcache\S1ObjectDefinitions.Common.InvisibleBlock.dll"...
Loading ObjectDefinition type S1ObjectDefinitions.GHZ.Bridge from "GHZ\Bridge.cs"...
Loading type from cached assembly "dllcache\S1ObjectDefinitions.GHZ.Bridge.dll"...
Loading ObjectDefinition type S1ObjectDefinitions.GHZ.SwingingPlatform from "GHZ\SwingingPlatform.cs"...
Loading type from cached assembly "dllcache\S1ObjectDefinitions.GHZ.SwingingPlatform.dll"...
Loading ObjectDefinition type S1ObjectDefinitions.GHZ.SpikedPole from "GHZ\SpikedPole.cs"...
Loading type from cached assembly "dllcache\S1ObjectDefinitions.GHZ.SpikedPole.dll"...
Loading start position "Level Start" from file "../startpos/ghz3.bin"...
Loading objects from file "../objpos/ghz3.bin", using compression Uncompressed...
Error loading start position definition Level Start:
System.ArgumentException: Source array was not long enough. Check srcIndex and length, and the array's lower bounds.
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at SonicRetro.SonLVL.API.ByteConverter.ToInt16(Byte[] value, Int32 startIndex) in E:\AutoBuild\SonLVL\SonLVLAPI\ByteConverter.cs:line 61
   at SonicRetro.SonLVL.API.LevelData.GetOffsetList(Byte[] file) in E:\AutoBuild\SonLVL\SonLVLAPI\LevelData.cs:line 1668
   at SonicRetro.SonLVL.API.MappingsFrame.Load(Byte[] file, EngineVersion version, Dictionary`2 labels) in E:\AutoBuild\SonLVL\SonLVLAPI\DataTypes.cs:line 1378
   at SonicRetro.SonLVL.API.ObjectHelper.MapDPLCToBmp(Byte[] artfile, Byte[] mapfile, EngineVersion mapversion, Byte[] dplc, EngineVersion dplcversion, Int32 frame, Int32 startpal, Boolean priority) in E:\AutoBuild\SonLVL\SonLVLAPI\ObjectHelper.cs:line 39
   at SonicRetro.SonLVL.API.ObjectHelper.MapASMDPLCToBmp(Byte[] artfile, String mapfileloc, EngineVersion mapversion, String dplcloc, EngineVersion dplcversion, Int32 frame, Int32 startpal, Boolean priority) in E:\AutoBuild\SonLVL\SonLVLAPI\ObjectHelper.cs:line 70
   at SonicRetro.SonLVL.API.StartPositionDefinition..ctor(ObjectData data, String name) in E:\AutoBuild\SonLVL\SonLVLAPI\ObjectDefinition.cs:line 1328
Drawing block bitmaps...
Drawing chunk bitmaps...
Level loaded in 0.4254778 second(s).
Load completed.
Saving Green Hill Zone Act 3...
Loading Labyrinth Zone Act 1...
Loading 16x16 blocks from file "../map16/LZ.bin", using compression Enigma...
Loading 8x8 tiles from file "../artnem/8x8 - LZ.bin", using compression Nemesis...
Loading 256x256 chunks from file "../map256/LZ.bin", using compression Kosinski...
Loading FG layout from file "../levels/lz1.bin", using compression Uncompressed...
Loading BG layout from file "../levels/lzbg.bin", using compression Uncompressed...
Loading palette file "../palette/Sonic.bin"...
Source: 0 Destination: 0 Length: 16
Loading palette file "../palette/Labyrinth Zone.bin"...
Source: 0 Destination: 16 Length: 48
Loading palette file "../palette/Labyrinth Zone Underwater.bin"...
Source: 0 Destination: 0 Length: 64
Loading FG layout from file "../levels/lz2.bin", using compression Uncompressed...
Loading FG layout from file "../levels/lz3.bin", using compression Uncompressed...
Loading FG layout from file "../levels/sbz3.bin", using compression Uncompressed...
Loading object definition file "obj.ini".
Loading object definition file "objLZ.ini".
Loading ObjectDefinition type S1ObjectDefinitions.Common.Ring from "Common\Ring.cs"...
Loading type from cached assembly "dllcache\S1ObjectDefinitions.Common.Ring.dll"...
Loading ObjectDefinition type S1ObjectDefinitions.Common.InvisibleBlock from "Common\InvisibleBlock.cs"...
Loading type from cached assembly "dllcache\S1ObjectDefinitions.Common.InvisibleBlock.dll"...
Loading ObjectDefinition type S1ObjectDefinitions.LZ.Spikeball from "LZ\Spikeball.cs"...
Loading type from cached assembly "dllcache\S1ObjectDefinitions.LZ.Spikeball.dll"...
Loading type from cached assembly "dllcache\S1ObjectDefinitions.LZ.Bubbles.dll"...
System.AggregateException: One or more errors occurred. ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at SonicRetro.SonLVL.API.MappingsTile..ctor(Byte[] file, Int32 address, EngineVersion version) in E:\AutoBuild\SonLVL\SonLVLAPI\DataTypes.cs:line 1284
   at SonicRetro.SonLVL.API.MappingsFrame..ctor(Byte[] file, Int32 address, EngineVersion version, String name) in E:\AutoBuild\SonLVL\SonLVLAPI\DataTypes.cs:line 1414
   at SonicRetro.SonLVL.API.MappingsFrame.Load(Byte[] file, EngineVersion version, Dictionary`2 labels) in E:\AutoBuild\SonLVL\SonLVLAPI\DataTypes.cs:line 1387
   at SonicRetro.SonLVL.API.ObjectHelper.MapToBmp(Byte[] artfile, Byte[] mapfile, Int32 frame, Int32 startpal, Boolean priority, EngineVersion version) in E:\AutoBuild\SonLVL\SonLVLAPI\ObjectHelper.cs:line 10
   at SonicRetro.SonLVL.API.ObjectHelper.MapASMToBmp(Byte[] artfile, String mapfileloc, Int32 frame, Int32 startpal, Boolean priority, EngineVersion version) in E:\AutoBuild\SonLVL\SonLVLAPI\ObjectHelper.cs:line 18
   at SonicRetro.SonLVL.API.XMLObjectDefinition.Init(ObjectData data) in E:\AutoBuild\SonLVL\SonLVLAPI\ObjectDefinition.cs:line 710
   at SonicRetro.SonLVL.API.LevelData.<>c__DisplayClass100_0.<InitObjectDefinitions>b__0(KeyValuePair`2 group) in E:\AutoBuild\SonLVL\SonLVLAPI\LevelData.cs:line 1508
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at SonicRetro.SonLVL.API.LevelData.InitObjectDefinitions() in E:\AutoBuild\SonLVL\SonLVLAPI\LevelData.cs:line 1435
   at SonicRetro.SonLVL.API.LevelData.LoadLevel(String levelname, Boolean loadGraphics) in E:\AutoBuild\SonLVL\SonLVLAPI\LevelData.cs:line 304
   at SonicRetro.SonLVL.GUI.MainForm.backgroundLevelLoader_DoWork(Object sender, DoWorkEventArgs e) in E:\AutoBuild\SonLVL\SonLVL\MainForm.cs:line 561
---> (Inner Exception #0) System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at SonicRetro.SonLVL.API.MappingsTile..ctor(Byte[] file, Int32 address, EngineVersion version) in E:\AutoBuild\SonLVL\SonLVLAPI\DataTypes.cs:line 1284
   at SonicRetro.SonLVL.API.MappingsFrame..ctor(Byte[] file, Int32 address, EngineVersion version, String name) in E:\AutoBuild\SonLVL\SonLVLAPI\DataTypes.cs:line 1414
   at SonicRetro.SonLVL.API.MappingsFrame.Load(Byte[] file, EngineVersion version, Dictionary`2 labels) in E:\AutoBuild\SonLVL\SonLVLAPI\DataTypes.cs:line 1387
   at SonicRetro.SonLVL.API.ObjectHelper.MapToBmp(Byte[] artfile, Byte[] mapfile, Int32 frame, Int32 startpal, Boolean priority, EngineVersion version) in E:\AutoBuild\SonLVL\SonLVLAPI\ObjectHelper.cs:line 10
   at SonicRetro.SonLVL.API.ObjectHelper.MapASMToBmp(Byte[] artfile, String mapfileloc, Int32 frame, Int32 startpal, Boolean priority, EngineVersion version) in E:\AutoBuild\SonLVL\SonLVLAPI\ObjectHelper.cs:line 18
   at SonicRetro.SonLVL.API.XMLObjectDefinition.Init(ObjectData data) in E:\AutoBuild\SonLVL\SonLVLAPI\ObjectDefinition.cs:line 710
   at SonicRetro.SonLVL.API.LevelData.<>c__DisplayClass100_0.<InitObjectDefinitions>b__0(KeyValuePair`2 group) in E:\AutoBuild\SonLVL\SonLVLAPI\LevelData.cs:line 1508
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

Loading Labyrinth Zone Act 1...
Loading 8x8 tiles from file "../artnem/8x8 - LZ.bin", using compression Nemesis...
Loading 16x16 blocks from file "../map16/LZ.bin", using compression Enigma...
Loading 256x256 chunks from file "../map256/LZ.bin", using compression Kosinski...
Loading palette file "../palette/Sonic.bin"...
Source: 0 Destination: 0 Length: 16
Loading FG layout from file "../levels/lz1.bin", using compression Uncompressed...
Loading BG layout from file "../levels/lzbg.bin", using compression Uncompressed...
Loading palette file "../palette/Labyrinth Zone.bin"...
Source: 0 Destination: 16 Length: 48
Loading palette file "../palette/Labyrinth Zone Underwater.bin"...
Source: 0 Destination: 0 Length: 64
Loading FG layout from file "../levels/lz2.bin", using compression Uncompressed...
Loading FG layout from file "../levels/lz3.bin", using compression Uncompressed...
Loading FG layout from file "../levels/sbz3.bin", using compression Uncompressed...
Loading object definition file "obj.ini".
Loading object definition file "objLZ.ini".
Loading ObjectDefinition type S1ObjectDefinitions.Common.Ring from "Common\Ring.cs"...
Loading type from cached assembly "dllcache\S1ObjectDefinitions.Common.Ring.dll"...
Loading ObjectDefinition type S1ObjectDefinitions.Common.InvisibleBlock from "Common\InvisibleBlock.cs"...
Loading type from cached assembly "dllcache\S1ObjectDefinitions.Common.InvisibleBlock.dll"...
System.AggregateException: One or more errors occurred. ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at SonicRetro.SonLVL.API.MappingsTile..ctor(Byte[] file, Int32 address, EngineVersion version) in E:\AutoBuild\SonLVL\SonLVLAPI\DataTypes.cs:line 1284
   at SonicRetro.SonLVL.API.MappingsFrame..ctor(Byte[] file, Int32 address, EngineVersion version, String name) in E:\AutoBuild\SonLVL\SonLVLAPI\DataTypes.cs:line 1414
   at SonicRetro.SonLVL.API.MappingsFrame.Load(Byte[] file, EngineVersion version, Dictionary`2 labels) in E:\AutoBuild\SonLVL\SonLVLAPI\DataTypes.cs:line 1387
   at SonicRetro.SonLVL.API.ObjectHelper.MapToBmp(Byte[] artfile, Byte[] mapfile, Int32 frame, Int32 startpal, Boolean priority, EngineVersion version) in E:\AutoBuild\SonLVL\SonLVLAPI\ObjectHelper.cs:line 10
   at SonicRetro.SonLVL.API.ObjectHelper.MapASMToBmp(Byte[] artfile, String mapfileloc, Int32 frame, Int32 startpal, Boolean priority, EngineVersion version) in E:\AutoBuild\SonLVL\SonLVLAPI\ObjectHelper.cs:line 18
   at SonicRetro.SonLVL.API.XMLObjectDefinition.Init(ObjectData data) in E:\AutoBuild\SonLVL\SonLVLAPI\ObjectDefinition.cs:line 710
   at SonicRetro.SonLVL.API.LevelData.<>c__DisplayClass100_0.<InitObjectDefinitions>b__0(KeyValuePair`2 group) in E:\AutoBuild\SonLVL\SonLVLAPI\LevelData.cs:line 1508
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at SonicRetro.SonLVL.API.LevelData.InitObjectDefinitions() in E:\AutoBuild\SonLVL\SonLVLAPI\LevelData.cs:line 1435
   at SonicRetro.SonLVL.API.LevelData.LoadLevel(String levelname, Boolean loadGraphics) in E:\AutoBuild\SonLVL\SonLVLAPI\LevelData.cs:line 304
   at SonicRetro.SonLVL.GUI.MainForm.backgroundLevelLoader_DoWork(Object sender, DoWorkEventArgs e) in E:\AutoBuild\SonLVL\SonLVL\MainForm.cs:line 561
---> (Inner Exception #0) System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at SonicRetro.SonLVL.API.MappingsTile..ctor(Byte[] file, Int32 address, EngineVersion version) in E:\AutoBuild\SonLVL\SonLVLAPI\DataTypes.cs:line 1284
   at SonicRetro.SonLVL.API.MappingsFrame..ctor(Byte[] file, Int32 address, EngineVersion version, String name) in E:\AutoBuild\SonLVL\SonLVLAPI\DataTypes.cs:line 1414
   at SonicRetro.SonLVL.API.MappingsFrame.Load(Byte[] file, EngineVersion version, Dictionary`2 labels) in E:\AutoBuild\SonLVL\SonLVLAPI\DataTypes.cs:line 1387
   at SonicRetro.SonLVL.API.ObjectHelper.MapToBmp(Byte[] artfile, Byte[] mapfile, Int32 frame, Int32 startpal, Boolean priority, EngineVersion version) in E:\AutoBuild\SonLVL\SonLVLAPI\ObjectHelper.cs:line 10
   at SonicRetro.SonLVL.API.ObjectHelper.MapASMToBmp(Byte[] artfile, String mapfileloc, Int32 frame, Int32 startpal, Boolean priority, EngineVersion version) in E:\AutoBuild\SonLVL\SonLVLAPI\ObjectHelper.cs:line 18
   at SonicRetro.SonLVL.API.XMLObjectDefinition.Init(ObjectData data) in E:\AutoBuild\SonLVL\SonLVLAPI\ObjectDefinition.cs:line 710
   at SonicRetro.SonLVL.API.LevelData.<>c__DisplayClass100_0.<InitObjectDefinitions>b__0(KeyValuePair`2 group) in E:\AutoBuild\SonLVL\SonLVLAPI\LevelData.cs:line 1508
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

"

If anyone has a fix for this, I'd gladly appreciate it, because editing the zones in another disasm and THEN copying it over to ReadySonic is getting tedious.

**Comment by MainMemory** [comment]
ReadySonic is not supported in SonLVL. Mercury applied some options into the sprite mapping files that break SonLVL's parser. You can edit the affected files to remove the conditional statements and then SonLVL will be able to read them.
