### ISSUE TITLE
SonLVL wont load Launch base act 1

### ISSUE THREAD

**Issue by 0Lupus0** [sonicretro/SonLVL#59]
Program: SonLVL
Build Date: 01/19/2019 22:16:04
OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
Log:
Operating system: Microsoft Windows NT 6.1.7601 Service Pack 1
Opening INI file "C:\Users\Kiddos\Desktop\Sonic 3k hack\skdisasm-master\SonLVL INI Files\SonLVL.ini"...
Game type is S3K.
Loading Launch Base Zone Act 1...
Loading 16x16 blocks from file "../Levels/LBZ/Blocks/Primary.bin", using compression Kosinski...
Loading 128x128 chunks from file "../Levels/LBZ/Chunks/Act 1.bin", using compression Kosinski...
Loading palette file "../General/Sprites/Sonic/Palettes/SonicAndTails.bin"...
Source: 0 Destination: 0 Length: 16
Loading palette file "../Levels/LBZ/Palettes/1.bin"...
Source: 0 Destination: 16 Length: 48
Loading 16x16 blocks from file "../Levels/LBZ/Blocks/Act 1 Secondary.bin", using compression Kosinski...
Loading layout from file "../Levels/LBZ/Layout/1.bin", using compression Uncompressed...
Loading 8x8 tiles from file "../Levels/LBZ/Tiles/Primary.bin", using compression KosinskiM...
Loading 8x8 tiles from file "../Levels/LBZ/Tiles/Act 1 Secondary.bin", using compression KosinskiM...
Loading extra color file "../General/Sprites/Knuckles/Palettes/Main.bin"...
Source: 0 Destination: 0 Length: 16
Loading extra color file "../Levels/LBZ/Palettes/Miniboss.bin"...
Source: 0 Destination: 16 Length: 16
Loading extra color file "../General/Sprites/Knuckles/Cutscene/Pal.bin"...
Source: 0 Destination: 48 Length: 16
Loading object definition file "Common/Main.ini".
Loading object definition file "Common/1P.ini".
Loading object definition file "LBZ/Main.ini".
Loading object definition file "LBZ/E.ini".
Loading object definition file "LBZ/1.ini".
Loading object definition file "LBZ/1E.ini".
Loading ObjectDefinition type S3KObjectDefinitions.Common.Monitor from "Common\Monitor.cs"...
Loading ObjectDefinition type S3KObjectDefinitions.Common.InvisibleHurtBlockHorizontal from "Common\InvisibleBlock.cs"...
Loading ObjectDefinition type S3KObjectDefinitions.Common.PathSwap from "Common\PathSwap.cs"...
Loading ObjectDefinition type S3KObjectDefinitions.Common.InvisibleHurtBlockVertical from "Common\InvisibleBlock.cs"...
Loading ObjectDefinition type S3KObjectDefinitions.Common.Spring from "Common\Spring.cs"...
Loading ObjectDefinition type S3KObjectDefinitions.Common.InvisibleBlock from "Common\InvisibleBlock.cs"...
Loading type from cached assembly "dllcache\S3KObjectDefinitions.Common.Monitor.dll"...
Loading type from cached assembly "dllcache\S3KObjectDefinitions.Common.InvisibleHurtBlockHorizontal.dll"...
Loading type from cached assembly "dllcache\S3KObjectDefinitions.Common.InvisibleHurtBlockVertical.dll"...
Loading type from cached assembly "dllcache\S3KObjectDefinitions.Common.PathSwap.dll"...
Loading type from cached assembly "dllcache\S3KObjectDefinitions.Common.InvisibleBlock.dll"...
Loading type from cached assembly "dllcache\S3KObjectDefinitions.Common.Spring.dll"...
Loading ObjectDefinition type S3KObjectDefinitions.Common.Spikes from "Common\Spikes.cs"...
Loading type from cached assembly "dllcache\S3KObjectDefinitions.Common.Spikes.dll"...
Loading ObjectDefinition type S3KObjectDefinitions.LBZ.CollapsingBridge from "Common\CollapsingBridge.cs"...
Loading type from cached assembly "dllcache\S3KObjectDefinitions.LBZ.CollapsingBridge.dll"...
Loading ObjectDefinition type S3KObjectDefinitions.LBZ.MovingPlatform from "Common\FloatingPlatform.cs"...
Loading type from cached assembly "dllcache\S3KObjectDefinitions.LBZ.MovingPlatform.dll"...
Loading ObjectDefinition type S3KObjectDefinitions.LBZ.TriggerBridge from "LBZ\TriggerBridge.cs"...
Loading type from cached assembly "dllcache\S3KObjectDefinitions.LBZ.TriggerBridge.dll"...
Loading ObjectDefinition type S3KObjectDefinitions.LBZ.RideGrapple from "LBZ\RideGrapple.cs"...
Loading type from cached assembly "dllcache\S3KObjectDefinitions.LBZ.RideGrapple.dll"...
Loading ObjectDefinition type S3KObjectDefinitions.LBZ.CupElevatorPole from "LBZ\CupElevatorPole.cs"...
Loading type from cached assembly "dllcache\S3KObjectDefinitions.LBZ.CupElevatorPole.dll"...
Loading ObjectDefinition type S3KObjectDefinitions.LBZ.CupElevator from "LBZ\CupElevator.cs"...
Loading type from cached assembly "dllcache\S3KObjectDefinitions.LBZ.CupElevator.dll"...
Loading ObjectDefinition type S3KObjectDefinitions.LBZ.FlybotAlarm from "LBZ\FlybotAlarm.cs"...
Loading type from cached assembly "dllcache\S3KObjectDefinitions.LBZ.FlybotAlarm.dll"...
Loading ObjectDefinition type S3KObjectDefinitions.LBZ.CorkFloor from "Common\CorkFloor.cs"...
Loading type from cached assembly "dllcache\S3KObjectDefinitions.LBZ.CorkFloor.dll"...
Loading ObjectDefinition type S3KObjectDefinitions.LBZ.StillSprite from "Common\StillSprite.cs"...
Loading type from cached assembly "dllcache\S3KObjectDefinitions.LBZ.StillSprite.dll"...
Loading ObjectDefinition type S3KObjectDefinitions.LBZ.RollingDrum from "LBZ\RollingDrum.cs"...
Loading type from cached assembly "dllcache\S3KObjectDefinitions.LBZ.RollingDrum.dll"...
Loading ObjectDefinition type S3KObjectDefinitions.LBZ.SmashingPillar from "Common\MGZLBZSmashingPillar.cs"...
Loading type from cached assembly "dllcache\S3KObjectDefinitions.LBZ.SmashingPillar.dll"...
Loading ObjectDefinition type S3KObjectDefinitions.LBZ.TubeElevator from "Common\AutomaticTunnel.cs"...
Loading type from cached assembly "dllcache\S3KObjectDefinitions.LBZ.TubeElevator.dll"...
Loading ObjectDefinition type S3KObjectDefinitions.LBZ.Corkey from "LBZ\Corkey.cs"...
Loading type from cached assembly "dllcache\S3KObjectDefinitions.LBZ.Corkey.dll"...
Loading ObjectDefinition type S3KObjectDefinitions.Common.AutomaticTunnel from "Common\AutomaticTunnel.cs"...
Loading type from cached assembly "dllcache\S3KObjectDefinitions.Common.AutomaticTunnel.dll"...
Loading ObjectDefinition type S3KObjectDefinitions.Common.CutsceneKnuckles from "Common\CutsceneKnuckles.cs"...
Loading type from cached assembly "dllcache\S3KObjectDefinitions.Common.CutsceneKnuckles.dll"...
Loading ObjectDefinition type S3KObjectDefinitions.LBZ.Ribot from "LBZ\Ribot.cs"...
Loading type from cached assembly "dllcache\S3KObjectDefinitions.LBZ.Ribot.dll"...
Unable to read file "../General/Sprites/Enemy Misc/Badnik Explosion.bin" with compression KosinskiM:
System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Could not find file 'C:\Users\Kiddos\Desktop\Sonic 3k hack\skdisasm-master\General\Sprites\Enemy Misc\Badnik Explosion.bin'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at SonicRetro.KensSharp.ModuledKosinski.Decompress(String sourceFilePath, Endianness headerEndianness)
   at SonicRetro.SonLVL.API.Compression.Decompress(String file, CompressionType cmp) in E:\Programs\SonLVL\SonLVLAPI\Compression.cs:line 51
   at SonicRetro.SonLVL.API.LevelData.ReadFile(String file, CompressionType cmp) in E:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 1623
   at S3KObjectDefinitions.Common.CutsceneKnuckles.BuildSpritesSubtypes(Int32 startpal, Boolean s3, String girderart) in c:\Users\Kiddos\Desktop\Sonic 3k hack\skdisasm-master\SonLVL INI Files\Common\CutsceneKnuckles.cs:line 161
   at S3KObjectDefinitions.Common.CutsceneKnuckles.Init(ObjectData data) in c:\Users\Kiddos\Desktop\Sonic 3k hack\skdisasm-master\SonLVL INI Files\Common\CutsceneKnuckles.cs:line 107
   at SonicRetro.SonLVL.API.LevelData.<>c__DisplayClass102_0.<InitObjectDefinitions>b__0(KeyValuePair`2 group) in E:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 1563
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at SonicRetro.SonLVL.API.LevelData.InitObjectDefinitions() in E:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 1490
   at SonicRetro.SonLVL.API.LevelData.LoadLevel(String levelname, Boolean loadGraphics) in E:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 306
   at SonicRetro.SonLVL.GUI.MainForm.backgroundLevelLoader_DoWork(Object sender, DoWorkEventArgs e) in E:\Programs\SonLVL\SonLVL\MainForm.cs:line 567
---> (Inner Exception #0) System.IO.FileNotFoundException: Could not find file 'C:\Users\Kiddos\Desktop\Sonic 3k hack\skdisasm-master\General\Sprites\Enemy Misc\Badnik Explosion.bin'.
File name: 'C:\Users\Kiddos\Desktop\Sonic 3k hack\skdisasm-master\General\Sprites\Enemy Misc\Badnik Explosion.bin'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at SonicRetro.KensSharp.ModuledKosinski.Decompress(String sourceFilePath, Endianness headerEndianness)
   at SonicRetro.SonLVL.API.Compression.Decompress(String file, CompressionType cmp) in E:\Programs\SonLVL\SonLVLAPI\Compression.cs:line 51
   at SonicRetro.SonLVL.API.LevelData.ReadFile(String file, CompressionType cmp) in E:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 1623
   at S3KObjectDefinitions.Common.CutsceneKnuckles.BuildSpritesSubtypes(Int32 startpal, Boolean s3, String girderart) in c:\Users\Kiddos\Desktop\Sonic 3k hack\skdisasm-master\SonLVL INI Files\Common\CutsceneKnuckles.cs:line 161
   at S3KObjectDefinitions.Common.CutsceneKnuckles.Init(ObjectData data) in c:\Users\Kiddos\Desktop\Sonic 3k hack\skdisasm-master\SonLVL INI Files\Common\CutsceneKnuckles.cs:line 107
   at SonicRetro.SonLVL.API.LevelData.<>c__DisplayClass102_0.<InitObjectDefinitions>b__0(KeyValuePair`2 group) in E:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 1563
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

Loading Launch Base Zone Act 1...
Loading 16x16 blocks from file "../Levels/LBZ/Blocks/Primary.bin", using compression Kosinski...
Loading palette file "../General/Sprites/Sonic/Palettes/SonicAndTails.bin"...
Source: 0 Destination: 0 Length: 16
Loading 128x128 chunks from file "../Levels/LBZ/Chunks/Act 1.bin", using compression Kosinski...
Loading palette file "../Levels/LBZ/Palettes/1.bin"...
Source: 0 Destination: 16 Length: 48
Loading 16x16 blocks from file "../Levels/LBZ/Blocks/Act 1 Secondary.bin", using compression Kosinski...
Loading 8x8 tiles from file "../Levels/LBZ/Tiles/Primary.bin", using compression KosinskiM...
Loading 8x8 tiles from file "../Levels/LBZ/Tiles/Act 1 Secondary.bin", using compression KosinskiM...
Loading layout from file "../Levels/LBZ/Layout/1.bin", using compression Uncompressed...
Loading extra color file "../General/Sprites/Knuckles/Palettes/Main.bin"...
Source: 0 Destination: 0 Length: 16
Loading extra color file "../Levels/LBZ/Palettes/Miniboss.bin"...
Source: 0 Destination: 16 Length: 16
Loading extra color file "../General/Sprites/Knuckles/Cutscene/Pal.bin"...
Source: 0 Destination: 48 Length: 16
Loading object definition file "Common/Main.ini".
Loading object definition file "Common/1P.ini".
Loading object definition file "LBZ/Main.ini".
Loading object definition file "LBZ/E.ini".
Loading object definition file "LBZ/1.ini".
Loading object definition file "LBZ/1E.ini".
Loading ObjectDefinition type S3KObjectDefinitions.Common.PathSwap from "Common\PathSwap.cs"...
Loading type from cached assembly "dllcache\S3KObjectDefinitions.Common.PathSwap.dll"...
Loading ObjectDefinition type S3KObjectDefinitions.Common.InvisibleHurtBlockHorizontal from "Common\InvisibleBlock.cs"...
Loading ObjectDefinition type S3KObjectDefinitions.Common.InvisibleHurtBlockVertical from "Common\InvisibleBlock.cs"...
Loading ObjectDefinition type S3KObjectDefinitions.Common.Monitor from "Common\Monitor.cs"...
Loading type from cached assembly "dllcache\S3KObjectDefinitions.Common.Monitor.dll"...
Loading ObjectDefinition type S3KObjectDefinitions.Common.Spring from "Common\Spring.cs"...
Loading type from cached assembly "dllcache\S3KObjectDefinitions.Common.Spring.dll"...
Loading ObjectDefinition type S3KObjectDefinitions.Common.Spikes from "Common\Spikes.cs"...
Loading type from cached assembly "dllcache\S3KObjectDefinitions.Common.Spikes.dll"...
Loading ObjectDefinition type S3KObjectDefinitions.LBZ.CollapsingBridge from "Common\CollapsingBridge.cs"...
Loading type from cached assembly "dllcache\S3KObjectDefinitions.LBZ.CollapsingBridge.dll"...
Loading ObjectDefinition type S3KObjectDefinitions.LBZ.MovingPlatform from "Common\FloatingPlatform.cs"...
Loading type from cached assembly "dllcache\S3KObjectDefinitions.LBZ.MovingPlatform.dll"...
Loading ObjectDefinition type S3KObjectDefinitions.LBZ.TriggerBridge from "LBZ\TriggerBridge.cs"...
Loading type from cached assembly "dllcache\S3KObjectDefinitions.LBZ.TriggerBridge.dll"...
Loading ObjectDefinition type S3KObjectDefinitions.LBZ.RideGrapple from "LBZ\RideGrapple.cs"...
Loading type from cached assembly "dllcache\S3KObjectDefinitions.LBZ.RideGrapple.dll"...
Loading ObjectDefinition type S3KObjectDefinitions.LBZ.CupElevator from "LBZ\CupElevator.cs"...
Loading type from cached assembly "dllcache\S3KObjectDefinitions.LBZ.CupElevator.dll"...
Loading ObjectDefinition type S3KObjectDefinitions.LBZ.FlybotAlarm from "LBZ\FlybotAlarm.cs"...
Loading ObjectDefinition type S3KObjectDefinitions.LBZ.CorkFloor from "Common\CorkFloor.cs"...
Loading type from cached assembly "dllcache\S3KObjectDefinitions.LBZ.FlybotAlarm.dll"...
Loading ObjectDefinition type S3KObjectDefinitions.LBZ.CupElevatorPole from "LBZ\CupElevatorPole.cs"...
Loading type from cached assembly "dllcache\S3KObjectDefinitions.LBZ.CorkFloor.dll"...
Loading ObjectDefinition type S3KObjectDefinitions.LBZ.RollingDrum from "LBZ\RollingDrum.cs"...
Loading type from cached assembly "dllcache\S3KObjectDefinitions.LBZ.CupElevatorPole.dll"...
Loading type from cached assembly "dllcache\S3KObjectDefinitions.LBZ.RollingDrum.dll"...
Loading type from cached assembly "dllcache\S3KObjectDefinitions.Common.InvisibleHurtBlockHorizontal.dll"...
Loading ObjectDefinition type S3KObjectDefinitions.LBZ.Ribot from "LBZ\Ribot.cs"...
Loading type from cached assembly "dllcache\S3KObjectDefinitions.LBZ.Ribot.dll"...
Loading ObjectDefinition type S3KObjectDefinitions.LBZ.Corkey from "LBZ\Corkey.cs"...
Loading type from cached assembly "dllcache\S3KObjectDefinitions.LBZ.Corkey.dll"...
Loading ObjectDefinition type S3KObjectDefinitions.LBZ.TubeElevator from "Common\AutomaticTunnel.cs"...
Loading type from cached assembly "dllcache\S3KObjectDefinitions.LBZ.TubeElevator.dll"...
Loading ObjectDefinition type S3KObjectDefinitions.Common.AutomaticTunnel from "Common\AutomaticTunnel.cs"...
Loading type from cached assembly "dllcache\S3KObjectDefinitions.Common.AutomaticTunnel.dll"...
Loading ObjectDefinition type S3KObjectDefinitions.Common.HiddenMonitor from "Common\Monitor.cs"...
Loading type from cached assembly "dllcache\S3KObjectDefinitions.Common.HiddenMonitor.dll"...
Loading ObjectDefinition type S3KObjectDefinitions.Common.CutsceneKnuckles from "Common\CutsceneKnuckles.cs"...
Loading type from cached assembly "dllcache\S3KObjectDefinitions.Common.CutsceneKnuckles.dll"...
Loading ObjectDefinition type S3KObjectDefinitions.LBZ.StillSprite from "Common\StillSprite.cs"...
Loading type from cached assembly "dllcache\S3KObjectDefinitions.LBZ.StillSprite.dll"...
Loading type from cached assembly "dllcache\S3KObjectDefinitions.Common.InvisibleHurtBlockVertical.dll"...
Loading ObjectDefinition type S3KObjectDefinitions.Common.InvisibleBlock from "Common\InvisibleBlock.cs"...
Loading type from cached assembly "dllcache\S3KObjectDefinitions.Common.InvisibleBlock.dll"...
Unable to read file "../General/Sprites/Enemy Misc/Badnik Explosion.bin" with compression KosinskiM:
System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Could not find file 'C:\Users\Kiddos\Desktop\Sonic 3k hack\skdisasm-master\General\Sprites\Enemy Misc\Badnik Explosion.bin'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at SonicRetro.KensSharp.ModuledKosinski.Decompress(String sourceFilePath, Endianness headerEndianness)
   at SonicRetro.SonLVL.API.Compression.Decompress(String file, CompressionType cmp) in E:\Programs\SonLVL\SonLVLAPI\Compression.cs:line 51
   at SonicRetro.SonLVL.API.LevelData.ReadFile(String file, CompressionType cmp) in E:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 1623
   at S3KObjectDefinitions.Common.CutsceneKnuckles.BuildSpritesSubtypes(Int32 startpal, Boolean s3, String girderart) in c:\Users\Kiddos\Desktop\Sonic 3k hack\skdisasm-master\SonLVL INI Files\Common\CutsceneKnuckles.cs:line 161
   at S3KObjectDefinitions.Common.CutsceneKnuckles.Init(ObjectData data) in c:\Users\Kiddos\Desktop\Sonic 3k hack\skdisasm-master\SonLVL INI Files\Common\CutsceneKnuckles.cs:line 107
   at SonicRetro.SonLVL.API.LevelData.<>c__DisplayClass102_0.<InitObjectDefinitions>b__0(KeyValuePair`2 group) in E:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 1563
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at SonicRetro.SonLVL.API.LevelData.InitObjectDefinitions() in E:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 1490
   at SonicRetro.SonLVL.API.LevelData.LoadLevel(String levelname, Boolean loadGraphics) in E:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 306
   at SonicRetro.SonLVL.GUI.MainForm.backgroundLevelLoader_DoWork(Object sender, DoWorkEventArgs e) in E:\Programs\SonLVL\SonLVL\MainForm.cs:line 567
---> (Inner Exception #0) System.IO.FileNotFoundException: Could not find file 'C:\Users\Kiddos\Desktop\Sonic 3k hack\skdisasm-master\General\Sprites\Enemy Misc\Badnik Explosion.bin'.
File name: 'C:\Users\Kiddos\Desktop\Sonic 3k hack\skdisasm-master\General\Sprites\Enemy Misc\Badnik Explosion.bin'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at SonicRetro.KensSharp.ModuledKosinski.Decompress(String sourceFilePath, Endianness headerEndianness)
   at SonicRetro.SonLVL.API.Compression.Decompress(String file, CompressionType cmp) in E:\Programs\SonLVL\SonLVLAPI\Compression.cs:line 51
   at SonicRetro.SonLVL.API.LevelData.ReadFile(String file, CompressionType cmp) in E:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 1623
   at S3KObjectDefinitions.Common.CutsceneKnuckles.BuildSpritesSubtypes(Int32 startpal, Boolean s3, String girderart) in c:\Users\Kiddos\Desktop\Sonic 3k hack\skdisasm-master\SonLVL INI Files\Common\CutsceneKnuckles.cs:line 161
   at S3KObjectDefinitions.Common.CutsceneKnuckles.Init(ObjectData data) in c:\Users\Kiddos\Desktop\Sonic 3k hack\skdisasm-master\SonLVL INI Files\Common\CutsceneKnuckles.cs:line 107
   at SonicRetro.SonLVL.API.LevelData.<>c__DisplayClass102_0.<InitObjectDefinitions>b__0(KeyValuePair`2 group) in E:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 1563
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

**Comment by 0Lupus0** [comment]
this is specifically with the newest assembly of S3k
