### ISSUE TITLE
SonPLN Error

### ISSUE THREAD

**Issue by Akrenix** [sonicretro/SonLVL#73]
Program: SonPLN
Build Date: 11/26/2019 21:40:14
OS Version: Microsoft Windows NT 6.2.9200.0
Log:
Operating system: Microsoft Windows NT 6.2.9200.0
Opening INI file "s2disasm-master\SonLVL INI Files\SonicPLN.ini"...
Game type is S2.
Loading SEGA Logo...
Loading palette file "art/palettes/Sega screen.bin"...
Source: 16 Destination: 0 Length: 64
8x8 tile file "art/nemesis/SEGA.bin" not found.
Plane mappings file "mappings/misc/SEGA mappings.bin" not found.
System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
   at SonicRetro.SonLVL.SonPLN.MainForm.LoadLevelPalette() in E:\Programs\SonLVL\SonPLN\MainForm.cs:line 440
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.FastWaitAll(Task[] tasks)
   at System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions)
   at System.Threading.Tasks.Parallel.Invoke(Action[] actions)
   at SonicRetro.SonLVL.SonPLN.MainForm.backgroundLevelLoader_DoWork(Object sender, DoWorkEventArgs e) in E:\Programs\SonLVL\SonPLN\MainForm.cs:line 321
---> (Inner Exception #0) System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
File name: 'art/palettes/Sega screen.bin'
   at SonicRetro.SonLVL.SonPLN.MainForm.LoadLevelPalette() in E:\Programs\SonLVL\SonPLN\MainForm.cs:line 440
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by MainMemory** [comment]
Your palette file is missing.

**Comment by Akrenix** [comment]
> Your palette file is missing.

I have the palette file in the disassembly yet still gives me this error. Am I missing something more?

**Comment by death-rapunzel** [comment]
Try prefixing the paths with "../". It looks like your INI file is in a subfolder in your disassembly, yet your paths are set up as if the INI file was in the base folder.

**Comment by MainMemory** [comment]
Oh, right. The SonPLN INI should be in the disassembly root folder, don't move it unless you also change the paths in it.

**Comment by Akrenix** [comment]
> Try prefixing the paths with "../". It looks like your INI file is in a subfolder in your disassembly, yet your paths are set up as if the INI file was in the base folder.

Thank you. This helped a lot.
