### ISSUE TITLE
SonLVL Cannot load the pallete, which makes it stop loading the level.

### ISSUE THREAD

**Issue by ghost** [sonicretro/SonLVL#76]
Program: SonLVL
Build Date: 07/17/2020 14:44:44
OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
Log:
Operating system: Microsoft Windows NT 6.1.7601 Service Pack 1
Opening INI file "C:\Users\STAVROS\Desktop\Sonic Hack\s1disasm-master\SonLVL INI Files\SonLVL.ini"...
Game type is S1.
Loading Green Hill Zone Act 1...
256x256 chunk file "../map256/GHZ.bin" not found.
8x8 tile file "../artnem/8x8 - GHZ1.bin" not found.
16x16 block file "../map16/GHZ.bin" not found.
8x8 tile file "../artnem/8x8 - GHZ2.bin" not found.
FG layout file "../levels/ghz1.bin" not found.
Loading palette file "../palette/Sonic.bin"...
Source: 0 Destination: 0 Length: 16
BG layout file "../levels/ghzbg.bin" not found.
FG layout file "../levels/ghz2.bin" not found.
FG layout file "../levels/ghz3.bin" not found.
FG layout file "../levels/ending.bin" not found.
System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
   at SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() in E:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 689
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
   at System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions)
   at System.Threading.Tasks.Parallel.Invoke(Action[] actions)
   at SonicRetro.SonLVL.API.LevelData.LoadLevel(String levelname, Boolean loadGraphics) in E:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 179
   at SonicRetro.SonLVL.GUI.MainForm.backgroundLevelLoader_DoWork(Object sender, DoWorkEventArgs e) in E:\Programs\SonLVL\SonLVL\MainForm.cs:line 574
---> (Inner Exception #0) System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
File name: '../palette/Sonic.bin'
   at SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() in E:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 689
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

Loading Green Hill Zone Act 2...
256x256 chunk file "../map256/GHZ.bin" not found.
FG layout file "../levels/ghz2.bin" not found.
BG layout file "../levels/ghzbg.bin" not found.
FG layout file "../levels/ghz1.bin" not found.
16x16 block file "../map16/GHZ.bin" not found.
Loading palette file "../palette/Sonic.bin"...
Source: 0 Destination: 0 Length: 16
FG layout file "../levels/ghz3.bin" not found.
8x8 tile file "../artnem/8x8 - GHZ1.bin" not found.
8x8 tile file "../artnem/8x8 - GHZ2.bin" not found.
FG layout file "../levels/ending.bin" not found.
System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
   at SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() in E:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 689
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
   at System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions)
   at System.Threading.Tasks.Parallel.Invoke(Action[] actions)
   at SonicRetro.SonLVL.API.LevelData.LoadLevel(String levelname, Boolean loadGraphics) in E:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 179
   at SonicRetro.SonLVL.GUI.MainForm.backgroundLevelLoader_DoWork(Object sender, DoWorkEventArgs e) in E:\Programs\SonLVL\SonLVL\MainForm.cs:line 574
---> (Inner Exception #0) System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
File name: '../palette/Sonic.bin'
   at SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() in E:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 689
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

Loading Green Hill Zone Act 1...
8x8 tile file "../artnem/8x8 - GHZ1.bin" not found.
16x16 block file "../map16/GHZ.bin" not found.
Loading palette file "../palette/Sonic.bin"...
Source: 0 Destination: 0 Length: 16
256x256 chunk file "../map256/GHZ.bin" not found.
FG layout file "../levels/ghz1.bin" not found.
8x8 tile file "../artnem/8x8 - GHZ2.bin" not found.
BG layout file "../levels/ghzbg.bin" not found.
FG layout file "../levels/ghz2.bin" not found.
FG layout file "../levels/ghz3.bin" not found.
FG layout file "../levels/ending.bin" not found.
System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
   at SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() in E:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 689
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
   at System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions)
   at System.Threading.Tasks.Parallel.Invoke(Action[] actions)
   at SonicRetro.SonLVL.API.LevelData.LoadLevel(String levelname, Boolean loadGraphics) in E:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 179
   at SonicRetro.SonLVL.GUI.MainForm.backgroundLevelLoader_DoWork(Object sender, DoWorkEventArgs e) in E:\Programs\SonLVL\SonLVL\MainForm.cs:line 574
---> (Inner Exception #0) System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
File name: '../palette/Sonic.bin'
   at SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() in E:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 689
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

Loading Green Hill Zone Act 1...
16x16 block file "../map16/GHZ.bin" not found.
256x256 chunk file "../map256/GHZ.bin" not found.
FG layout file "../levels/ghz1.bin" not found.
Loading palette file "../palette/Sonic.bin"...
Source: 0 Destination: 0 Length: 16
BG layout file "../levels/ghzbg.bin" not found.
FG layout file "../levels/ghz2.bin" not found.
8x8 tile file "../artnem/8x8 - GHZ1.bin" not found.
8x8 tile file "../artnem/8x8 - GHZ2.bin" not found.
FG layout file "../levels/ghz3.bin" not found.
FG layout file "../levels/ending.bin" not found.
System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
   at SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() in E:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 689
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
   at System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions)
   at System.Threading.Tasks.Parallel.Invoke(Action[] actions)
   at SonicRetro.SonLVL.API.LevelData.LoadLevel(String levelname, Boolean loadGraphics) in E:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 179
   at SonicRetro.SonLVL.GUI.MainForm.backgroundLevelLoader_DoWork(Object sender, DoWorkEventArgs e) in E:\Programs\SonLVL\SonLVL\MainForm.cs:line 574
---> (Inner Exception #0) System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
File name: '../palette/Sonic.bin'
   at SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() in E:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 689
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by thomasthedank199** [comment]
I've had to exact same problem.

**Comment by GalaxytedYT** [comment]
### ### **_**_****_**_**
