### ISSUE TITLE
Cannot find palette files

### ISSUE THREAD

**Issue by BenTM1** [sonicretro/SonLVL#82]
AggregateException: One or more errors occurred. => FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?

Loading Angel Island Zone Act 2...
8x8 tile file "../Levels/AIZ/Tiles/Act 2 Primary.bin" not found.
8x8 tile file "../Levels/AIZ/Tiles/Act 2 Secondary.bin" not found.
Loading palette file "../General/Sprites/Sonic/Palettes/SonicAndTails.bin"...
Source: 0 Destination: 0 Length: 16
Layout file "../Levels/AIZ/Layout/2.bin" not found.
128x128 chunk file "../Levels/AIZ/Chunks/Act 2.bin" not found.
16x16 block file "../Levels/AIZ/Blocks/Act 2 Primary.bin" not found.
16x16 block file "../Levels/AIZ/Blocks/Act 2 Secondary.bin" not found.
System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
   at SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() in E:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 689
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
   at System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions)
   at System.Threading.Tasks.Parallel.Invoke(Action[] actions)
   at SonicRetro.SonLVL.API.LevelData.LoadLevel(String levelname, Boolean loadGraphics) in E:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 179
   at SonicRetro.SonLVL.GUI.MainForm.backgroundLevelLoader_DoWork(Object sender, DoWorkEventArgs e) in E:\Programs\SonLVL\SonLVL\MainForm.cs:line 574
---> (Inner Exception #0) System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
File name: '../General/Sprites/Sonic/Palettes/SonicAndTails.bin'
   at SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() in E:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 689
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by MainMemory** [comment]
It can't find any of the files it needs. The S3K disassembly on GitHub should be pre-split, so all the files should be there. It should come with SonLVL files too.
