### ISSUE TITLE
Levels and rom won't load up.

### ISSUE THREAD

**Issue by MarioYT21** [sonicretro/SonLVL#89]
Program: SonLVL
Build Date: 03/17/2021 20:45:46
OS Version: Microsoft Windows NT 6.2.9200.0
Log:
Operating system: Microsoft Windows NT 6.2.9200.0
Opening INI file "C:\Users\arese\OneDrive\Escritorio\Editing\skdisasm-master\SonLVL INI Files\SonLVL.ini"...
Game type is S3K.
Loading Carnival Night Zone Act 1...
Loading 16x16 blocks from file "../Levels/CNZ/Blocks/Primary.bin", using compression Kosinski...
Loading 8x8 tiles from file "../Levels/CNZ/Tiles/Primary.bin", using compression KosinskiM...
Loading 128x128 chunks from file "../Levels/CNZ/Chunks/Primary.bin", using compression Kosinski...
Loading layout from file "../Levels/CNZ/Layout/1.bin", using compression Uncompressed...
Loading palette file "../General/Sprites/Sonic/Palettes/SonicAndTails.bin"...
Source: 0 Destination: 0 Length: 16
Loading palette file "../Levels/CNZ/Palettes/Main.bin"...
Source: 0 Destination: 16 Length: 48
Loading palette file "../General/Sprites/Sonic/Palettes/SonicAndTails.bin"...
Source: 0 Destination: 0 Length: 16
Loading palette file "../Levels/CNZ/Palettes/Miniboss.bin"...
Source: 0 Destination: 16 Length: 16
Loading palette file "../Levels/CNZ/Palettes/Main.bin"...
Source: 16 Destination: 32 Length: 32
Loading layout from file "../Levels/CNZ/Layout/2.bin", using compression Uncompressed...
Loading extra color file "../General/Sprites/Knuckles/Palettes/Main.bin"...
Source: 0 Destination: 0 Length: 16
Loading object definition file "Common/Main.ini".
Loading object definition file "Common/1P.ini".
Loading object definition file "CNZ/Main.ini".
Loading object definition file "CNZ/E.ini".
Loading object definition file "CNZ/1.ini".
Loading object definition file "CNZ/1E.ini".
Loading ObjectDefinition type S3KObjectDefinitions.Common.PathSwap from "Common\PathSwap.cs"...
Loading ObjectDefinition type S3KObjectDefinitions.Common.InvisibleBlock from "Common\InvisibleBlock.cs"...
Loading type from cached assembly "dllcache\S3KObjectDefinitions.Common.InvisibleBlock.dll"...
Loading type from cached assembly "dllcache\S3KObjectDefinitions.Common.PathSwap.dll"...
Loading ObjectDefinition type S3KObjectDefinitions.Common.InvisibleHurtBlockHorizontal from "Common\InvisibleBlock.cs"...
Loading type from cached assembly "dllcache\S3KObjectDefinitions.Common.InvisibleHurtBlockHorizontal.dll"...
Loading ObjectDefinition type S3KObjectDefinitions.Common.InvisibleHurtBlockVertical from "Common\InvisibleBlock.cs"...
Loading type from cached assembly "dllcache\S3KObjectDefinitions.Common.InvisibleHurtBlockVertical.dll"...
Loading ObjectDefinition type S3KObjectDefinitions.Common.Monitor from "Common\Monitor.cs"...
Loading type from cached assembly "dllcache\S3KObjectDefinitions.Common.Monitor.dll"...
Unable to read file "../General/Sprites/HUD Icon/Sonic life icon.bin" with compression Nemesis:
System.AggregateException: One or more errors occurred. ---> SonicRetro.KensSharp.CompressionException: A bit code is already used as a prefix for other codes.
   at SonicRetro.KensSharp.Nemesis.DecodingCodeTreeNode.SetCode(Byte code, Int32 length, NibbleRun nibbleRun)
   at SonicRetro.KensSharp.Nemesis.DecodeHeader(Stream input, Stream output, DecodingCodeTreeNode codeTree)
   at SonicRetro.KensSharp.Nemesis.Decode(Stream input, Stream output)
   at SonicRetro.KensSharp.Nemesis.Decompress(Stream input, Stream output)
   at SonicRetro.KensSharp.Nemesis.Decompress(String sourceFilePath)
   at SonicRetro.SonLVL.API.Compression.Decompress(String file, CompressionType cmp) in D:\Programs\SonLVL\SonLVLAPI\Compression.cs:line 51
   at SonicRetro.SonLVL.API.LevelData.ReadFile(String file, CompressionType cmp) in D:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 1638
   at S3KObjectDefinitions.Common.Monitor.Init(ObjectData data) in c:\Users\arese\OneDrive\Escritorio\Editing\skdisasm-master\SonLVL INI Files\Common\Monitor.cs:line 70
   at SonicRetro.SonLVL.API.LevelData.<>c__DisplayClass102_0.<InitObjectDefinitions>b__0(KeyValuePair`2 group) in D:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 1578
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at SonicRetro.SonLVL.API.LevelData.InitObjectDefinitions() in D:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 1505
   at SonicRetro.SonLVL.API.LevelData.LoadLevel(String levelname, Boolean loadGraphics) in D:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 319
   at SonicRetro.SonLVL.GUI.MainForm.backgroundLevelLoader_DoWork(Object sender, DoWorkEventArgs e) in D:\Programs\SonLVL\SonLVL\MainForm.cs:line 574
---> (Inner Exception #0) SonicRetro.KensSharp.CompressionException: A bit code is already used as a prefix for other codes.
   at SonicRetro.KensSharp.Nemesis.DecodingCodeTreeNode.SetCode(Byte code, Int32 length, NibbleRun nibbleRun)
   at SonicRetro.KensSharp.Nemesis.DecodeHeader(Stream input, Stream output, DecodingCodeTreeNode codeTree)
   at SonicRetro.KensSharp.Nemesis.Decode(Stream input, Stream output)
   at SonicRetro.KensSharp.Nemesis.Decompress(Stream input, Stream output)
   at SonicRetro.KensSharp.Nemesis.Decompress(String sourceFilePath)
   at SonicRetro.SonLVL.API.Compression.Decompress(String file, CompressionType cmp) in D:\Programs\SonLVL\SonLVLAPI\Compression.cs:line 51
   at SonicRetro.SonLVL.API.LevelData.ReadFile(String file, CompressionType cmp) in D:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 1638
   at S3KObjectDefinitions.Common.Monitor.Init(ObjectData data) in c:\Users\arese\OneDrive\Escritorio\Editing\skdisasm-master\SonLVL INI Files\Common\Monitor.cs:line 70
   at SonicRetro.SonLVL.API.LevelData.<>c__DisplayClass102_0.<InitObjectDefinitions>b__0(KeyValuePair`2 group) in D:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 1578
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---

**Comment by MarioYT21** [comment]
Program: SonLVL
Build Date: 03/17/2021 20:45:46
OS Version: Microsoft Windows NT 6.2.9200.0
Log:
Operating system: Microsoft Windows NT 6.2.9200.0
Opening INI file "C:\Users\arese\OneDrive\Escritorio\Editing\skdisasm-master\SonLVL INI Files\SonLVL.ini"...
Game type is S3K.
Loading Launch Base Zone Act 1...
Loading 8x8 tiles from file "../Levels/LBZ/Tiles/Primary.bin", using compression KosinskiM...
Loading 128x128 chunks from file "../Levels/LBZ/Chunks/Act 1.bin", using compression Kosinski...
Loading 16x16 blocks from file "../Levels/LBZ/Blocks/Primary.bin", using compression Kosinski...
Loading layout from file "../Levels/LBZ/Layout/1.bin", using compression Uncompressed...
Loading 8x8 tiles from file "../Levels/LBZ/Tiles/Act 1 Secondary.bin", using compression KosinskiM...
Loading 16x16 blocks from file "../Levels/LBZ/Blocks/Act 1 Secondary.bin", using compression Kosinski...
Loading palette file "../General/Sprites/Sonic/Palettes/SonicAndTails.bin"...
Source: 0 Destination: 0 Length: 16
Loading palette file "../Levels/LBZ/Palettes/1.bin"...
Source: 0 Destination: 16 Length: 48
Loading extra color file "../General/Sprites/Knuckles/Palettes/Main.bin"...
Source: 0 Destination: 0 Length: 16
Loading extra color file "../Levels/LBZ/Palettes/Miniboss.bin"...
Source: 0 Destination: 16 Length: 16
Loading extra color file "../General/Sprites/Knuckles/Cutscene/Pal.bin"...
Source: 0 Destination: 48 Length: 16
Loading object definition file "Common/Main.ini".
Loading object definition file "Common/1P.ini".
Loading object definition file "LBZ/Main.ini".
Loading object definition file "LBZ/E.ini".
Loading object definition file "LBZ/1.ini".
Loading object definition file "LBZ/1E.ini".
Loading ObjectDefinition type S3KObjectDefinitions.Common.PathSwap from "Common\PathSwap.cs"...
Loading ObjectDefinition type S3KObjectDefinitions.Common.InvisibleBlock from "Common\InvisibleBlock.cs"...
Loading type from cached assembly "dllcache\S3KObjectDefinitions.Common.PathSwap.dll"...
Loading type from cached assembly "dllcache\S3KObjectDefinitions.Common.InvisibleBlock.dll"...
Loading ObjectDefinition type S3KObjectDefinitions.Common.InvisibleHurtBlockHorizontal from "Common\InvisibleBlock.cs"...
Loading type from cached assembly "dllcache\S3KObjectDefinitions.Common.InvisibleHurtBlockHorizontal.dll"...
Loading ObjectDefinition type S3KObjectDefinitions.Common.InvisibleHurtBlockVertical from "Common\InvisibleBlock.cs"...
Loading type from cached assembly "dllcache\S3KObjectDefinitions.Common.InvisibleHurtBlockVertical.dll"...
Loading ObjectDefinition type S3KObjectDefinitions.Common.Monitor from "Common\Monitor.cs"...
Loading type from cached assembly "dllcache\S3KObjectDefinitions.Common.Monitor.dll"...
Loading ObjectDefinition type S3KObjectDefinitions.Common.Spring from "Common\Spring.cs"...
Loading type from cached assembly "dllcache\S3KObjectDefinitions.Common.Spring.dll"...
Loading ObjectDefinition type S3KObjectDefinitions.Common.Spikes from "Common\Spikes.cs"...
Loading type from cached assembly "dllcache\S3KObjectDefinitions.Common.Spikes.dll"...
Unable to read file "../General/Sprites/HUD Icon/Sonic life icon.bin" with compression Nemesis:
System.AggregateException: One or more errors occurred. ---> SonicRetro.KensSharp.CompressionException: A bit code is already used as a prefix for other codes.
   at SonicRetro.KensSharp.Nemesis.DecodingCodeTreeNode.SetCode(Byte code, Int32 length, NibbleRun nibbleRun)
   at SonicRetro.KensSharp.Nemesis.DecodeHeader(Stream input, Stream output, DecodingCodeTreeNode codeTree)
   at SonicRetro.KensSharp.Nemesis.Decode(Stream input, Stream output)
   at SonicRetro.KensSharp.Nemesis.Decompress(Stream input, Stream output)
   at SonicRetro.KensSharp.Nemesis.Decompress(String sourceFilePath)
   at SonicRetro.SonLVL.API.Compression.Decompress(String file, CompressionType cmp) in D:\Programs\SonLVL\SonLVLAPI\Compression.cs:line 51
   at SonicRetro.SonLVL.API.LevelData.ReadFile(String file, CompressionType cmp) in D:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 1638
   at S3KObjectDefinitions.Common.Monitor.Init(ObjectData data) in c:\Users\arese\OneDrive\Escritorio\Editing\skdisasm-master\SonLVL INI Files\Common\Monitor.cs:line 70
   at SonicRetro.SonLVL.API.LevelData.<>c__DisplayClass102_0.<InitObjectDefinitions>b__0(KeyValuePair`2 group) in D:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 1578
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at SonicRetro.SonLVL.API.LevelData.InitObjectDefinitions() in D:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 1505
   at SonicRetro.SonLVL.API.LevelData.LoadLevel(String levelname, Boolean loadGraphics) in D:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 319
   at SonicRetro.SonLVL.GUI.MainForm.backgroundLevelLoader_DoWork(Object sender, DoWorkEventArgs e) in D:\Programs\SonLVL\SonLVL\MainForm.cs:line 574
---> (Inner Exception #0) SonicRetro.KensSharp.CompressionException: A bit code is already used as a prefix for other codes.
   at SonicRetro.KensSharp.Nemesis.DecodingCodeTreeNode.SetCode(Byte code, Int32 length, NibbleRun nibbleRun)
   at SonicRetro.KensSharp.Nemesis.DecodeHeader(Stream input, Stream output, DecodingCodeTreeNode codeTree)
   at SonicRetro.KensSharp.Nemesis.Decode(Stream input, Stream output)
   at SonicRetro.KensSharp.Nemesis.Decompress(Stream input, Stream output)
   at SonicRetro.KensSharp.Nemesis.Decompress(String sourceFilePath)
   at SonicRetro.SonLVL.API.Compression.Decompress(String file, CompressionType cmp) in D:\Programs\SonLVL\SonLVLAPI\Compression.cs:line 51
   at SonicRetro.SonLVL.API.LevelData.ReadFile(String file, CompressionType cmp) in D:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 1638
   at S3KObjectDefinitions.Common.Monitor.Init(ObjectData data) in c:\Users\arese\OneDrive\Escritorio\Editing\skdisasm-master\SonLVL INI Files\Common\Monitor.cs:line 70
   at SonicRetro.SonLVL.API.LevelData.<>c__DisplayClass102_0.<InitObjectDefinitions>b__0(KeyValuePair`2 group) in D:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 1578
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---

Saving Launch Base Zone Act 1...
System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at SonicRetro.SonLVL.API.LevelData.SaveLevelRings() in D:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 1164
   at System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.<Invoke>b__0()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions)
   at SonicRetro.SonLVL.API.LevelData.SaveLevel() in D:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 962
   at SonicRetro.SonLVL.GUI.MainForm.saveToolStripMenuItem_Click(Object sender, EventArgs e) in D:\Programs\SonLVL\SonLVL\MainForm.cs:line 912
   at SonicRetro.SonLVL.GUI.MainForm.buildAndRunToolStripMenuItem_Click(Object sender, EventArgs e) in D:\Programs\SonLVL\SonLVL\MainForm.cs:line 948
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at SonicRetro.SonLVL.API.LevelData.SaveLevelRings() in D:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 1164
   at System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.<Invoke>b__0()<---

---> (Inner Exception #1) System.NullReferenceException: Object reference not set to an instance of an object.
   at SonicRetro.SonLVL.API.LevelData.SaveLevelObjects() in D:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 1155
   at System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.<Invoke>b__0()<---

---> (Inner Exception #2) System.NullReferenceException: Object reference not set to an instance of an object.
   at SonicRetro.SonLVL.API.LevelData.SaveLevelStartPositions() in D:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 1201
   at System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.<Invoke>b__0()<---

Saving Launch Base Zone Act 1...
System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at SonicRetro.SonLVL.API.LevelData.SaveLevelRings() in D:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 1164
   at System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.<Invoke>b__0()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions)
   at SonicRetro.SonLVL.API.LevelData.SaveLevel() in D:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 962
   at SonicRetro.SonLVL.GUI.MainForm.saveToolStripMenuItem_Click(Object sender, EventArgs e) in D:\Programs\SonLVL\SonLVL\MainForm.cs:line 912
   at SonicRetro.SonLVL.GUI.MainForm.buildAndRunToolStripMenuItem_Click(Object sender, EventArgs e) in D:\Programs\SonLVL\SonLVL\MainForm.cs:line 948
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at SonicRetro.SonLVL.API.LevelData.SaveLevelRings() in D:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 1164
   at System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.<Invoke>b__0()<---

---> (Inner Exception #1) System.NullReferenceException: Object reference not set to an instance of an object.
   at SonicRetro.SonLVL.API.LevelData.SaveLevelObjects() in D:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 1155
   at System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.<Invoke>b__0()<---

---> (Inner Exception #2) System.NullReferenceException: Object reference not set to an instance of an object.
   at SonicRetro.SonLVL.API.LevelData.SaveLevelStartPositions() in D:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 1201
   at System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.<Invoke>b__0()<---

Saving Launch Base Zone Act 1...
System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at SonicRetro.SonLVL.API.LevelData.SaveLevelObjects() in D:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 1155
   at System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.<Invoke>b__0()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions)
   at SonicRetro.SonLVL.API.LevelData.SaveLevel() in D:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 962
   at SonicRetro.SonLVL.GUI.MainForm.saveToolStripMenuItem_Click(Object sender, EventArgs e) in D:\Programs\SonLVL\SonLVL\MainForm.cs:line 912
   at SonicRetro.SonLVL.GUI.MainForm.buildAndRunToolStripMenuItem_Click(Object sender, EventArgs e) in D:\Programs\SonLVL\SonLVL\MainForm.cs:line 948
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at SonicRetro.SonLVL.API.LevelData.SaveLevelObjects() in D:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 1155
   at System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.<Invoke>b__0()<---

---> (Inner Exception #1) System.NullReferenceException: Object reference not set to an instance of an object.
   at SonicRetro.SonLVL.API.LevelData.SaveLevelRings() in D:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 1164
   at System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.<Invoke>b__0()<---

---> (Inner Exception #2) System.NullReferenceException: Object reference not set to an instance of an object.
   at SonicRetro.SonLVL.API.LevelData.SaveLevelStartPositions() in D:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 1201
   at System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.<Invoke>b__0()<---

Saving Launch Base Zone Act 1...
System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at SonicRetro.SonLVL.API.LevelData.SaveLevelObjects() in D:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 1155
   at System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.<Invoke>b__0()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions)
   at SonicRetro.SonLVL.API.LevelData.SaveLevel() in D:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 962
   at SonicRetro.SonLVL.GUI.MainForm.saveToolStripMenuItem_Click(Object sender, EventArgs e) in D:\Programs\SonLVL\SonLVL\MainForm.cs:line 912
   at SonicRetro.SonLVL.GUI.MainForm.buildAndRunToolStripMenuItem_Click(Object sender, EventArgs e) in D:\Programs\SonLVL\SonLVL\MainForm.cs:line 948
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at SonicRetro.SonLVL.API.LevelData.SaveLevelObjects() in D:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 1155
   at System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.<Invoke>b__0()<---

---> (Inner Exception #1) System.NullReferenceException: Object reference not set to an instance of an object.
   at SonicRetro.SonLVL.API.LevelData.SaveLevelRings() in D:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 1164
   at System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.<Invoke>b__0()<---

---> (Inner Exception #2) System.NullReferenceException: Object reference not set to an instance of an object.
   at SonicRetro.SonLVL.API.LevelData.SaveLevelStartPositions() in D:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 1201
   at System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.<Invoke>b__0()<---
