### ISSUE TITLE
sonlvl cant load sonic 1 levels

### ISSUE THREAD

**Issue by CiaranKelly64** [sonicretro/SonLVL#99]
can anyone help me? im trying to load the sonic 1 levels in sonlvl but i get this error:Program: SonLVL
Build Date: 10/12/2021 18:23:18
OS Version: Microsoft Windows NT 6.2.9200.0
Log:
Operating system: Microsoft Windows NT 6.2.9200.0
Opening INI file "D:\SonLVL Updater\Sonic 1 Git INIs\SonLVL.ini"...
Game type is S1.
Loading Green Hill Zone Act 1...
Loading palette file "../palette/Sonic.bin"...
Source: 0 Destination: 0 Length: 16
256x256 chunk file "../map256/GHZ.bin" not found.
16x16 block file "../map16/GHZ.bin" not found.
8x8 tile file "../artnem/8x8 - GHZ1.bin" not found.
8x8 tile file "../artnem/8x8 - GHZ2.bin" not found.
FG layout file "../levels/ghz1.bin" not found.
BG layout file "../levels/ghzbg.bin" not found.
FG layout file "../levels/ghz2.bin" not found.
FG layout file "../levels/ghz3.bin" not found.
FG layout file "../levels/ending.bin" not found.
System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
   at SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() in D:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 689
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
   at System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions)
   at System.Threading.Tasks.Parallel.Invoke(Action[] actions)
   at SonicRetro.SonLVL.API.LevelData.LoadLevel(String levelname, Boolean loadGraphics) in D:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 184
   at SonicRetro.SonLVL.GUI.MainForm.backgroundLevelLoader_DoWork(Object sender, DoWorkEventArgs e) in D:\Programs\SonLVL\SonLVL\MainForm.cs:line 574
---> (Inner Exception #0) System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
File name: '../palette/Sonic.bin'
   at SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() in D:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 689
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

Opening INI file "D:\SonLVL Updater\Sonic 1 Git INIs\SonLVL.rev01.ini"...
Game type is S1.
Loading Green Hill Zone Act 2...
Loading palette file "../palette/Sonic.bin"...
Source: 0 Destination: 0 Length: 16
8x8 tile file "../artnem/8x8 - GHZ1.bin" not found.
16x16 block file "../map16/GHZ.bin" not found.
FG layout file "../levels/ghz2.bin" not found.
256x256 chunk file "../map256/GHZ.bin" not found.
8x8 tile file "../artnem/8x8 - GHZ2.bin" not found.
BG layout file "../levels/ghzbg.bin" not found.
FG layout file "../levels/ghz1.bin" not found.
FG layout file "../levels/ghz3.bin" not found.
FG layout file "../levels/ending.bin" not found.
System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
   at SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() in D:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 689
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
   at System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions)
   at System.Threading.Tasks.Parallel.Invoke(Action[] actions)
   at SonicRetro.SonLVL.API.LevelData.LoadLevel(String levelname, Boolean loadGraphics) in D:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 184
   at SonicRetro.SonLVL.GUI.MainForm.backgroundLevelLoader_DoWork(Object sender, DoWorkEventArgs e) in D:\Programs\SonLVL\SonLVL\MainForm.cs:line 574
---> (Inner Exception #0) System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
File name: '../palette/Sonic.bin'
   at SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() in D:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 689
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

Loading Green Hill Zone Act 1...
16x16 block file "../map16/GHZ.bin" not found.
256x256 chunk file "../map256/GHZ.bin" not found.
FG layout file "../levels/ghz1.bin" not found.
BG layout file "../levels/ghzbg.bin" not found.
Loading palette file "../palette/Sonic.bin"...
Source: 0 Destination: 0 Length: 16
FG layout file "../levels/ghz2.bin" not found.
8x8 tile file "../artnem/8x8 - GHZ1.bin" not found.
8x8 tile file "../artnem/8x8 - GHZ2.bin" not found.
FG layout file "../levels/ghz3.bin" not found.
FG layout file "../levels/ending.bin" not found.
System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
   at SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() in D:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 689
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
   at System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions)
   at System.Threading.Tasks.Parallel.Invoke(Action[] actions)
   at SonicRetro.SonLVL.API.LevelData.LoadLevel(String levelname, Boolean loadGraphics) in D:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 184
   at SonicRetro.SonLVL.GUI.MainForm.backgroundLevelLoader_DoWork(Object sender, DoWorkEventArgs e) in D:\Programs\SonLVL\SonLVL\MainForm.cs:line 574
---> (Inner Exception #0) System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
File name: '../palette/Sonic.bin'
   at SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() in D:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 689
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

Loading Green Hill Zone Act 2...
16x16 block file "../map16/GHZ.bin" not found.
256x256 chunk file "../map256/GHZ.bin" not found.
FG layout file "../levels/ghz2.bin" not found.
BG layout file "../levels/ghzbg.bin" not found.
Loading palette file "../palette/Sonic.bin"...
Source: 0 Destination: 0 Length: 16
8x8 tile file "../artnem/8x8 - GHZ1.bin" not found.
8x8 tile file "../artnem/8x8 - GHZ2.bin" not found.
FG layout file "../levels/ghz1.bin" not found.
FG layout file "../levels/ghz3.bin" not found.
FG layout file "../levels/ending.bin" not found.
System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
   at SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() in D:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 689
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
   at System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions)
   at System.Threading.Tasks.Parallel.Invoke(Action[] actions)
   at SonicRetro.SonLVL.API.LevelData.LoadLevel(String levelname, Boolean loadGraphics) in D:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 184
   at SonicRetro.SonLVL.GUI.MainForm.backgroundLevelLoader_DoWork(Object sender, DoWorkEventArgs e) in D:\Programs\SonLVL\SonLVL\MainForm.cs:line 574
---> (Inner Exception #0) System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
File name: '../palette/Sonic.bin'
   at SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() in D:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 689
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by Caverns4** [comment]
You're trying to load a SonLvl project file from outside the disassembly. That is not possible.
Your disassembly should come with a SonLvl folder built in. If so, load that. If not, just copy the entire "Sonic 1 Git INIs" folder you have the INI in into your disassembly project.
